
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USUARIO
 */
public class GUI extends javax.swing.JFrame {

   int mousex, mousey;
    public GUI() {
        
        initComponents();
        
      
       



   //    grafica_barras_1();

       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Barra1 = new javax.swing.JPanel();
        SalirBoton = new MiBoton();
        Titulo2 = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();
        Filtr = new javax.swing.JScrollPane();
        Filtrador = new javax.swing.JPanel();
        Busqueda6 = new MiBoton();
        Busqueda7 = new MiBoton();
        Busqueda8 = new MiBoton();
        Busqueda9 = new MiBoton();
        Busqueda11 = new MiBoton();
        Busqueda12 = new MiBoton();
        Busqueda13 = new MiBoton();
        Busqueda14 = new MiBoton();
        jButton1 = new MiBoton();
        Info = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setFocusTraversalPolicyProvider(true);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Barra1.setBackground(new java.awt.Color(255, 255, 255));
        Barra1.setFocusCycleRoot(true);
        Barra1.setOpaque(false);
        Barra1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Barra1MouseDragged(evt);
            }
        });
        Barra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Barra1MousePressed(evt);
            }
        });
        Barra1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SalirBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerca (2).png"))); // NOI18N
        SalirBoton.setContentAreaFilled(false);
        SalirBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBotonActionPerformed(evt);
            }
        });
        Barra1.add(SalirBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        Titulo2.setBackground(new java.awt.Color(255, 255, 255));
        Titulo2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        Titulo2.setForeground(new java.awt.Color(255, 255, 255));
        Titulo2.setText("Copu");
        Barra1.add(Titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        Titulo1.setBackground(new java.awt.Color(255, 102, 0));
        Titulo1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 102, 51));
        Titulo1.setText("Edu");
        Barra1.add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        jPanel1.add(Barra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 49));

        Filtr.setBorder(null);
        Filtr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Filtr.setOpaque(false);
        Filtr.getVerticalScrollBar().setUnitIncrement(20);
        //ocultar

        //ocultar

        Filtrador.setBackground(new java.awt.Color(0, 102, 102));
        Filtrador.setForeground(new java.awt.Color(0, 102, 102));
        Filtrador.setPreferredSize(new java.awt.Dimension(200, 1500));
        Filtrador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Busqueda6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        Busqueda6.setContentAreaFilled(false);
        Busqueda6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Filtrador.add(Busqueda6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        Busqueda7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        Busqueda7.setContentAreaFilled(false);
        Busqueda7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Filtrador.add(Busqueda7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        Busqueda8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        Busqueda8.setContentAreaFilled(false);
        Busqueda8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Filtrador.add(Busqueda8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        Busqueda9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        Busqueda9.setContentAreaFilled(false);
        Busqueda9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Filtrador.add(Busqueda9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        Busqueda11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        Busqueda11.setContentAreaFilled(false);
        Busqueda11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Filtrador.add(Busqueda11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, -1, -1));

        Busqueda12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        Busqueda12.setContentAreaFilled(false);
        Busqueda12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Filtrador.add(Busqueda12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, -1, -1));

        Busqueda13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        Busqueda13.setContentAreaFilled(false);
        Busqueda13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Filtrador.add(Busqueda13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 700, -1, -1));

        Busqueda14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        Busqueda14.setContentAreaFilled(false);
        Busqueda14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Filtrador.add(Busqueda14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 800, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/internet (1).png"))); // NOI18N
        jButton1.setText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>todos los  filtrados");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Filtrador.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 1290, 120, 170));

        Filtr.setViewportView(Filtrador);

        jPanel1.add(Filtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -18, 340, 640));

        Info.setBackground(new java.awt.Color(255, 255, 255));
        Info.setForeground(new java.awt.Color(255, 255, 255));
        Info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, -10, 730, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Barra1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra1MousePressed
        mousex=evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_Barra1MousePressed

    private void Barra1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-mousex, y-mousey);
    }//GEN-LAST:event_Barra1MouseDragged

    private void SalirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBotonActionPerformed
     System.exit(0);
    }//GEN-LAST:event_SalirBotonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra1;
    private javax.swing.JButton Busqueda11;
    private javax.swing.JButton Busqueda12;
    private javax.swing.JButton Busqueda13;
    private javax.swing.JButton Busqueda14;
    private javax.swing.JButton Busqueda6;
    private javax.swing.JButton Busqueda7;
    private javax.swing.JButton Busqueda8;
    private javax.swing.JButton Busqueda9;
    private javax.swing.JScrollPane Filtr;
    private javax.swing.JPanel Filtrador;
    private javax.swing.JPanel Info;
    private javax.swing.JButton SalirBoton;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
public  void  grafica_barras_1(){
    
    
       
       
        int datox=5;
        int datoy=10;
        int datoz=30;
        DefaultCategoryDataset datos = new DefaultCategoryDataset();
        datos.setValue(datox, "dato x", "nose x");
        datos.setValue(datoy, "dato x", "nose y");
         datos.setValue(datoz, "dato x", "nose z");
        

        JFreeChart grafico_1 = ChartFactory.createBarChart3D(
     "grafico 1",         //nombre del grafico
          "Datos x",      //nombre de las barras o columnas
         "resultados x",  //nombre de la numeracion
         datos,           //nombre de grafico
         PlotOrientation.HORIZONTAL,       //orientacion
         true,            //legenda de barras individuales por color
         true,          //url del grafico
         false
        );
        
        ChartPanel barras = new ChartPanel(grafico_1);
        barras.setMouseWheelEnabled(true);
        barras.setPreferredSize(new Dimension(0,300));
        barras.setLocation(0, 0);
    
       
        pack();
        repaint();
}

}

