
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSlider;
import javax.swing.SwingConstants;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;



/**
 *
 * @author USUARIO
 */

public class GUI extends javax.swing.JFrame {
          RegistrarVariablesCasillas obj = new RegistrarVariablesCasillas();
          RegistrarVariablesRadioButtons obj2 = new RegistrarVariablesRadioButtons();
       
    
   int mousex, mousey;
    public GUI() {
       
        initComponents();
           
      
       



   //    grafica_barras_1();

       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        grupoAños = new javax.swing.ButtonGroup();
        ID = new javax.swing.ButtonGroup();
        Generos = new javax.swing.ButtonGroup();
        ColegioGeneroGrupo = new javax.swing.ButtonGroup();
        AreaColegio = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Barra1 = new javax.swing.JPanel();
        SalirBoton = new MiBoton();
        Titulo2 = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();
        Filtr = new javax.swing.JScrollPane();
        Filtrador = new javax.swing.JPanel();
        BuscarAreaColegio = new MiBoton();
        BusquedaAños = new MiBoton();
        BuscarGeneroColegio = new MiBoton();
        Busquedatipodocumento = new MiBoton();
        BotonGenero = new MiBoton();
        Municipio = new MiBoton();
        BuscarDesempeñolectura = new MiBoton();
        jButton1 = new MiBoton();
        Busqueda10 = new MiBoton();
        Busqueda15 = new MiBoton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        año2020 = new javax.swing.JCheckBox();
        año2019 = new javax.swing.JCheckBox();
        Masculino = new javax.swing.JCheckBox();
        año2018 = new javax.swing.JCheckBox();
        Cedula = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JSeparator();
        Noconozcomisgenitales = new javax.swing.JCheckBox();
        TarjetaIdentidad = new javax.swing.JCheckBox();
        Femenino = new javax.swing.JCheckBox();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        AreaTodos = new javax.swing.JCheckBox();
        todosaño = new javax.swing.JCheckBox();
        TodosTipodeDocumentos = new javax.swing.JCheckBox();
        desempeñoingles = new javax.swing.JComboBox<>();
        jSeparator8 = new javax.swing.JSeparator();
        municipiosselec = new javax.swing.JComboBox<>();
        TodosGeneros = new javax.swing.JCheckBox();
        ColegiogeneroMIXTO = new javax.swing.JCheckBox();
        ColegiogeneroFEMENINO = new javax.swing.JCheckBox();
        ColegiogeneroMasculino = new javax.swing.JCheckBox();
        jSeparator10 = new javax.swing.JSeparator();
        ColegiogeneroTODOS = new javax.swing.JCheckBox();
        AreaRural = new javax.swing.JCheckBox();
        AreaUrbana = new javax.swing.JCheckBox();
        jSeparator11 = new javax.swing.JSeparator();
        Plectura = new javax.swing.JSlider();
        jSeparator12 = new javax.swing.JSeparator();
        Busqueda14 = new MiBoton();
        Busqueda21 = new MiBoton();
        jSeparator13 = new javax.swing.JSeparator();
        Busqueda16 = new MiBoton();
        Busqueda22 = new MiBoton();
        jSeparator14 = new javax.swing.JSeparator();
        Busqueda17 = new MiBoton();
        Busqueda23 = new MiBoton();
        jSeparator15 = new javax.swing.JSeparator();
        Busqueda18 = new MiBoton();
        Busqueda19 = new MiBoton();
        modo = new javax.swing.JToggleButton();
        radioañostodos = new javax.swing.JRadioButton();
        radioaño2020 = new javax.swing.JRadioButton();
        radioaño2019 = new javax.swing.JRadioButton();
        radioaño2018 = new javax.swing.JRadioButton();
        Radiodocumentocedula = new javax.swing.JRadioButton();
        RadiodocumentoTodos = new javax.swing.JRadioButton();
        RadiodocumentoID1 = new javax.swing.JRadioButton();
        RadioTodosGeneros = new javax.swing.JRadioButton();
        RadioMasculino1 = new javax.swing.JRadioButton();
        RadioFemenino1 = new javax.swing.JRadioButton();
        RadioNoidentificadoporningungenero1 = new javax.swing.JRadioButton();
        RadioGeneroColegioTodos = new javax.swing.JRadioButton();
        RadioGeneroColegioMixto1 = new javax.swing.JRadioButton();
        RadioGeneroColegioFemenino = new javax.swing.JRadioButton();
        RadioGeneroColegioMasculino = new javax.swing.JRadioButton();
        RadioTodosArea = new javax.swing.JRadioButton();
        RadioRural = new javax.swing.JRadioButton();
        RadioUrbana = new javax.swing.JRadioButton();
        jSeparator18 = new javax.swing.JSeparator();
        Plectura1 = new javax.swing.JSlider();
        Plectura3 = new javax.swing.JSlider();
        Plectura4 = new javax.swing.JSlider();
        Plectura5 = new javax.swing.JSlider();
        putajeglobalbarra = new JSlider(JSlider.HORIZONTAL, 0, 500, 0);
        Estractoselect = new javax.swing.JComboBox<>();
        desempeñolectura1 = new javax.swing.JComboBox<>();
        desempeñomatematica1 = new javax.swing.JComboBox<>();
        desempeñonaturales1 = new javax.swing.JComboBox<>();
        PuntajeGlobal = new javax.swing.JSpinner();
        CamPG = new javax.swing.JToggleButton();
        Info = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setFocusTraversalPolicyProvider(true);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Barra1.setBackground(new java.awt.Color(255, 255, 255));
        Barra1.setFocusCycleRoot(true);
        Barra1.setOpaque(false);
        Barra1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Barra1MouseDragged(evt);
            }
        });
        Barra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Barra1MousePressed(evt);
            }
        });
        Barra1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SalirBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerca (2).png"))); // NOI18N
        SalirBoton.setContentAreaFilled(false);
        SalirBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBotonActionPerformed(evt);
            }
        });
        Barra1.add(SalirBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        Titulo2.setBackground(new java.awt.Color(255, 255, 255));
        Titulo2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        Titulo2.setForeground(new java.awt.Color(255, 255, 255));
        Titulo2.setText("Copu");
        Barra1.add(Titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        Titulo1.setBackground(new java.awt.Color(255, 102, 0));
        Titulo1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 102, 51));
        Titulo1.setText("Edu");
        Barra1.add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        jPanel1.add(Barra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 49));

        Filtr.setBorder(null);
        Filtr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Filtr.setOpaque(false);
        Filtr.getVerticalScrollBar().setUnitIncrement(20);
        //ocultar

        //ocultar

        Filtrador.setBackground(new java.awt.Color(0, 102, 102));
        Filtrador.setForeground(new java.awt.Color(0, 102, 102));
        Filtrador.setMinimumSize(new java.awt.Dimension(278, 3000));
        Filtrador.setPreferredSize(new java.awt.Dimension(200, 4300));
        Filtrador.setRequestFocusEnabled(false);
        Filtrador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BuscarAreaColegio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        BuscarAreaColegio.setToolTipText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>Filtrar");
        BuscarAreaColegio.setContentAreaFilled(false);
        BuscarAreaColegio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BuscarAreaColegio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarAreaColegioActionPerformed(evt);
            }
        });
        Filtrador.add(BuscarAreaColegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 1250, -1, -1));

        BusquedaAños.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        BusquedaAños.setToolTipText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>Filtrar");
        BusquedaAños.setContentAreaFilled(false);
        BusquedaAños.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BusquedaAños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaAñosActionPerformed(evt);
            }
        });
        Filtrador.add(BusquedaAños, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        BuscarGeneroColegio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        BuscarGeneroColegio.setToolTipText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>Filtrar");
        BuscarGeneroColegio.setContentAreaFilled(false);
        BuscarGeneroColegio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BuscarGeneroColegio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarGeneroColegioActionPerformed(evt);
            }
        });
        Filtrador.add(BuscarGeneroColegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 1020, -1, -1));

        Busquedatipodocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        Busquedatipodocumento.setToolTipText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>Filtrar");
        Busquedatipodocumento.setContentAreaFilled(false);
        Busquedatipodocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Busquedatipodocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedatipodocumentoActionPerformed(evt);
            }
        });
        Filtrador.add(Busquedatipodocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, -1, -1));

        BotonGenero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        BotonGenero.setToolTipText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>Filtrar");
        BotonGenero.setContentAreaFilled(false);
        BotonGenero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGeneroActionPerformed(evt);
            }
        });
        Filtrador.add(BotonGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 730, -1, -1));

        Municipio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        Municipio.setToolTipText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>Filtrar");
        Municipio.setContentAreaFilled(false);
        Municipio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Municipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MunicipioActionPerformed(evt);
            }
        });
        Filtrador.add(Municipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 1470, -1, -1));

        BuscarDesempeñolectura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        BuscarDesempeñolectura.setToolTipText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>Filtrar");
        BuscarDesempeñolectura.setContentAreaFilled(false);
        BuscarDesempeñolectura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BuscarDesempeñolectura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarDesempeñolecturaActionPerformed(evt);
            }
        });
        Filtrador.add(BuscarDesempeñolectura, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 2120, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/filtrar (3).png"))); // NOI18N
        jButton1.setText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>todos los  filtrados");
        jButton1.setToolTipText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>Filtrar todos los elementos<br>seleccionados");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Filtrador.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 4110, 120, 170));

        Busqueda10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        Busqueda10.setToolTipText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>Filtrar");
        Busqueda10.setContentAreaFilled(false);
        Busqueda10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Filtrador.add(Busqueda10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 1930, -1, -1));

        Busqueda15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        Busqueda15.setToolTipText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>Filtrar");
        Busqueda15.setContentAreaFilled(false);
        Busqueda15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Busqueda15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Busqueda15ActionPerformed(evt);
            }
        });
        Filtrador.add(Busqueda15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 1710, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("percentil");
        Filtrador.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 3820, 260, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Año");
        Filtrador.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 260, 50));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Genero");
        Filtrador.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 260, 50));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Municipio");
        Filtrador.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1320, 260, 50));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Estracto");
        Filtrador.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1540, 260, 50));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("Genero del colegio");
        Filtrador.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 810, 260, 50));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("area del colegio");
        Filtrador.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1090, 260, 50));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("puntaje lectura");
        Filtrador.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1780, 260, 50));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("desempeño lectura");
        Filtrador.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1970, 260, 50));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setText("puntaje matematica");
        Filtrador.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2200, 260, 50));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("desempeño matematicas");
        Filtrador.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2420, 260, 50));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 0));
        jLabel13.setText("desempeño naturales");
        Filtrador.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2860, 260, 50));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 102, 0));
        jLabel14.setText("puntaje naturales");
        Filtrador.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2650, 260, 50));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 102, 0));
        jLabel15.setText("puntaje ingles");
        Filtrador.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 3090, 260, 50));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 0));
        jLabel16.setText("desempeño ingles ");
        Filtrador.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 3320, 260, 50));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 102, 0));
        jLabel17.setText("puntaje gloval:");
        Filtrador.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 3610, 260, 50));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 102, 0));
        jLabel18.setText("Tipo de documento");
        Filtrador.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 260, 50));

        año2020.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        año2020.setForeground(new java.awt.Color(255, 255, 255));
        año2020.setText("2020");
        año2020.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                año2020ActionPerformed(evt);
            }
        });
        Filtrador.add(año2020, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        año2019.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        año2019.setForeground(new java.awt.Color(255, 255, 255));
        año2019.setText("2019");
        año2019.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                año2019ActionPerformed(evt);
            }
        });
        Filtrador.add(año2019, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        Masculino.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Masculino.setForeground(new java.awt.Color(255, 255, 255));
        Masculino.setText("Masculino");
        Masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasculinoActionPerformed(evt);
            }
        });
        Filtrador.add(Masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, -1, -1));

        año2018.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        año2018.setForeground(new java.awt.Color(255, 255, 255));
        año2018.setText("2018");
        año2018.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                año2018ActionPerformed(evt);
            }
        });
        Filtrador.add(año2018, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        Cedula.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Cedula.setForeground(new java.awt.Color(255, 255, 255));
        Cedula.setText("Cedula");
        Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaActionPerformed(evt);
            }
        });
        Filtrador.add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));
        Filtrador.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1780, 260, 10));

        Noconozcomisgenitales.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Noconozcomisgenitales.setForeground(new java.awt.Color(255, 255, 255));
        Noconozcomisgenitales.setText("No identificado");
        Noconozcomisgenitales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoconozcomisgenitalesActionPerformed(evt);
            }
        });
        Filtrador.add(Noconozcomisgenitales, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 700, -1, -1));

        TarjetaIdentidad.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TarjetaIdentidad.setForeground(new java.awt.Color(255, 255, 255));
        TarjetaIdentidad.setText("Tarjeta de identidad");
        TarjetaIdentidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarjetaIdentidadActionPerformed(evt);
            }
        });
        Filtrador.add(TarjetaIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        Femenino.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Femenino.setForeground(new java.awt.Color(255, 255, 255));
        Femenino.setText("Femenino");
        Femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemeninoActionPerformed(evt);
            }
        });
        Filtrador.add(Femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 660, -1, -1));
        Filtrador.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 260, 10));
        Filtrador.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 260, 10));

        AreaTodos.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        AreaTodos.setForeground(new java.awt.Color(255, 255, 255));
        AreaTodos.setText("Todos");
        AreaTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaTodosActionPerformed(evt);
            }
        });
        Filtrador.add(AreaTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1260, -1, -1));

        todosaño.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        todosaño.setForeground(new java.awt.Color(255, 255, 255));
        todosaño.setText("Todos");
        todosaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosañoActionPerformed(evt);
            }
        });
        Filtrador.add(todosaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        TodosTipodeDocumentos.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TodosTipodeDocumentos.setForeground(new java.awt.Color(255, 255, 255));
        TodosTipodeDocumentos.setText("Todos");
        TodosTipodeDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodosTipodeDocumentosActionPerformed(evt);
            }
        });
        Filtrador.add(TodosTipodeDocumentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        desempeñoingles.setBackground(new java.awt.Color(0, 102, 102));
        desempeñoingles.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        desempeñoingles.setForeground(new java.awt.Color(255, 102, 0));
        desempeñoingles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A-", "A1", "A2", "A2+", "B1", "B1+", "B2", "B2+", "C1", "C2" }));
        Filtrador.add(desempeñoingles, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 3390, 180, 50));
        Filtrador.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1320, 260, 10));

        municipiosselec.setBackground(new java.awt.Color(0, 102, 102));
        municipiosselec.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        municipiosselec.setForeground(new java.awt.Color(255, 102, 0));
        municipiosselec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amazonas", "Antioquia", "Arauca", "Atlántico", "Bolívar", "Boyacá", "Caldas", "Caquetá", "Casanare", "Cauca", "Cesar", "Chocó", "Córdoba", "Cundinamarca", "Guainía", "Guaviare", "Huila", "La Guajira", "Magdalena", "Meta", "Nariño", "Norte de Santander", "Putumayo", "Quindío", "Risaralda", "San Andrés y Providencia", "Santander", "Sucre", "Tolima", "Valle del Cauca", "Vaupés", "Vichada" }));
        Filtrador.add(municipiosselec, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1380, 180, 50));

        TodosGeneros.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TodosGeneros.setForeground(new java.awt.Color(255, 255, 255));
        TodosGeneros.setText("Todos");
        TodosGeneros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodosGenerosActionPerformed(evt);
            }
        });
        Filtrador.add(TodosGeneros, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 740, -1, -1));

        ColegiogeneroMIXTO.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ColegiogeneroMIXTO.setForeground(new java.awt.Color(255, 255, 255));
        ColegiogeneroMIXTO.setText("Mixto");
        ColegiogeneroMIXTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColegiogeneroMIXTOActionPerformed(evt);
            }
        });
        Filtrador.add(ColegiogeneroMIXTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 880, -1, -1));

        ColegiogeneroFEMENINO.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ColegiogeneroFEMENINO.setForeground(new java.awt.Color(255, 255, 255));
        ColegiogeneroFEMENINO.setText("Femenino");
        ColegiogeneroFEMENINO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColegiogeneroFEMENINOActionPerformed(evt);
            }
        });
        Filtrador.add(ColegiogeneroFEMENINO, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 930, -1, -1));

        ColegiogeneroMasculino.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ColegiogeneroMasculino.setForeground(new java.awt.Color(255, 255, 255));
        ColegiogeneroMasculino.setText("Masculino");
        ColegiogeneroMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColegiogeneroMasculinoActionPerformed(evt);
            }
        });
        Filtrador.add(ColegiogeneroMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 980, -1, -1));
        Filtrador.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 2200, 260, 10));

        ColegiogeneroTODOS.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ColegiogeneroTODOS.setForeground(new java.awt.Color(255, 255, 255));
        ColegiogeneroTODOS.setText("Todos");
        ColegiogeneroTODOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColegiogeneroTODOSActionPerformed(evt);
            }
        });
        Filtrador.add(ColegiogeneroTODOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1030, -1, -1));

        AreaRural.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        AreaRural.setForeground(new java.awt.Color(255, 255, 255));
        AreaRural.setText("Rural");
        AreaRural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaRuralActionPerformed(evt);
            }
        });
        Filtrador.add(AreaRural, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1160, -1, -1));

        AreaUrbana.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        AreaUrbana.setForeground(new java.awt.Color(255, 255, 255));
        AreaUrbana.setText("Urbana");
        AreaUrbana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaUrbanaActionPerformed(evt);
            }
        });
        Filtrador.add(AreaUrbana, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1210, -1, -1));
        Filtrador.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 810, 260, 10));

        Plectura.setMajorTickSpacing(10); // Espaciado entre las marcas principales
        Plectura.setPaintTicks(true); // Dibuja las marcas
        Plectura.setPaintLabels(true);
        Plectura.setValue(0);

        Plectura.setMajorTickSpacing(10);
        Plectura.setBackground(new java.awt.Color(255, 102, 0));
        Plectura.setForeground(new java.awt.Color(255, 255, 255));
        Filtrador.add(Plectura, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 2290, 250, -1));
        Filtrador.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1540, 260, 10));

        Busqueda14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        Busqueda14.setToolTipText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>Filtrar");
        Busqueda14.setContentAreaFilled(false);
        Busqueda14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Filtrador.add(Busqueda14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 2360, -1, -1));

        Busqueda21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        Busqueda21.setToolTipText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>Filtrar");
        Busqueda21.setContentAreaFilled(false);
        Busqueda21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Busqueda21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Busqueda21ActionPerformed(evt);
            }
        });
        Filtrador.add(Busqueda21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 2570, -1, -1));
        Filtrador.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 2640, 260, 10));

        Busqueda16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        Busqueda16.setToolTipText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>Filtrar");
        Busqueda16.setContentAreaFilled(false);
        Busqueda16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Busqueda16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Busqueda16ActionPerformed(evt);
            }
        });
        Filtrador.add(Busqueda16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 3010, -1, -1));

        Busqueda22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        Busqueda22.setToolTipText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>Filtrar");
        Busqueda22.setContentAreaFilled(false);
        Busqueda22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Filtrador.add(Busqueda22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 3250, -1, -1));
        Filtrador.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 3560, 260, 10));

        Busqueda17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        Busqueda17.setToolTipText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>Filtrar");
        Busqueda17.setContentAreaFilled(false);
        Busqueda17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Filtrador.add(Busqueda17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 2800, -1, -1));

        Busqueda23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        Busqueda23.setToolTipText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>Filtrar");
        Busqueda23.setContentAreaFilled(false);
        Busqueda23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Busqueda23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Busqueda23ActionPerformed(evt);
            }
        });
        Filtrador.add(Busqueda23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 3470, -1, -1));
        Filtrador.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 3090, 260, 10));

        Busqueda18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        Busqueda18.setToolTipText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>Filtrar");
        Busqueda18.setContentAreaFilled(false);
        Busqueda18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Filtrador.add(Busqueda18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 3750, -1, -1));

        Busqueda19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/revisar.png"))); // NOI18N
        Busqueda19.setToolTipText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>Filtrar");
        Busqueda19.setContentAreaFilled(false);
        Busqueda19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Filtrador.add(Busqueda19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 4020, -1, -1));

        modo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/apagar.png"))); // NOI18N
        modo.setText("<html><center><font face='Century Gothic' size = '4' color='white'><b>Varias opciones");
        modo.setToolTipText("<html><center><font face='Century Gothic' size = '4' color='orange'><b>Convierte todas las casillas de<br>seleccion multiple en<br>radiobuttons");
        modo.setContentAreaFilled(false);
        modo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modo.setHideActionText(true);
        modo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoActionPerformed(evt);
            }
        });
        Filtrador.add(modo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 110, -1));

        radioañostodos.setVisible(false);
        radioañostodos.setBackground(new java.awt.Color(0, 102, 102));
        grupoAños.add(radioañostodos);
        radioañostodos.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        radioañostodos.setForeground(new java.awt.Color(255, 255, 255));
        radioañostodos.setText("Todos");
        radioañostodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioañostodosActionPerformed(evt);
            }
        });
        Filtrador.add(radioañostodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        radioañostodos.setVisible(false);
        radioaño2020.setBackground(new java.awt.Color(0, 102, 102));
        grupoAños.add(radioaño2020);
        radioaño2020.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        radioaño2020.setForeground(new java.awt.Color(255, 255, 255));
        radioaño2020.setText("2020");
        Filtrador.add(radioaño2020, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        radioañostodos.setVisible(false);
        radioaño2019.setBackground(new java.awt.Color(0, 102, 102));
        grupoAños.add(radioaño2019);
        radioaño2019.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        radioaño2019.setForeground(new java.awt.Color(255, 255, 255));
        radioaño2019.setText("2019");
        Filtrador.add(radioaño2019, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        radioañostodos.setVisible(false);
        radioaño2018.setBackground(new java.awt.Color(0, 102, 102));
        grupoAños.add(radioaño2018);
        radioaño2018.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        radioaño2018.setForeground(new java.awt.Color(255, 255, 255));
        radioaño2018.setText("2018");
        radioaño2018.setToolTipText("");
        Filtrador.add(radioaño2018, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        Radiodocumentocedula.setBackground(new java.awt.Color(0, 102, 102));
        ID.add(Radiodocumentocedula);
        Radiodocumentocedula.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Radiodocumentocedula.setForeground(new java.awt.Color(255, 255, 255));
        Radiodocumentocedula.setText("Cedula\n");
        Filtrador.add(Radiodocumentocedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        RadiodocumentoTodos.setBackground(new java.awt.Color(0, 102, 102));
        ID.add(RadiodocumentoTodos);
        RadiodocumentoTodos.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        RadiodocumentoTodos.setForeground(new java.awt.Color(255, 255, 255));
        RadiodocumentoTodos.setText("Todos");
        Filtrador.add(RadiodocumentoTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        RadiodocumentoID1.setBackground(new java.awt.Color(0, 102, 102));
        ID.add(RadiodocumentoID1);
        RadiodocumentoID1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        RadiodocumentoID1.setForeground(new java.awt.Color(255, 255, 255));
        RadiodocumentoID1.setText("Tarjeta de identidad");
        Filtrador.add(RadiodocumentoID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        Generos.add(RadioTodosGeneros);
        RadioTodosGeneros.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        RadioTodosGeneros.setForeground(new java.awt.Color(255, 255, 255));
        RadioTodosGeneros.setText("Todos");
        Filtrador.add(RadioTodosGeneros, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 740, -1, -1));

        Generos.add(RadioMasculino1);
        RadioMasculino1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        RadioMasculino1.setForeground(new java.awt.Color(255, 255, 255));
        RadioMasculino1.setText("Masculino");
        Filtrador.add(RadioMasculino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, -1, -1));

        Generos.add(RadioFemenino1);
        RadioFemenino1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        RadioFemenino1.setForeground(new java.awt.Color(255, 255, 255));
        RadioFemenino1.setText("Femenino");
        Filtrador.add(RadioFemenino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 660, -1, -1));

        Generos.add(RadioNoidentificadoporningungenero1);
        RadioNoidentificadoporningungenero1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        RadioNoidentificadoporningungenero1.setForeground(new java.awt.Color(255, 255, 255));
        RadioNoidentificadoporningungenero1.setText("No identificado");
        Filtrador.add(RadioNoidentificadoporningungenero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 700, -1, -1));

        ColegioGeneroGrupo.add(RadioGeneroColegioTodos);
        RadioGeneroColegioTodos.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        RadioGeneroColegioTodos.setForeground(new java.awt.Color(255, 255, 255));
        RadioGeneroColegioTodos.setText("Todos");
        Filtrador.add(RadioGeneroColegioTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1030, -1, -1));

        ColegioGeneroGrupo.add(RadioGeneroColegioMixto1);
        RadioGeneroColegioMixto1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        RadioGeneroColegioMixto1.setForeground(new java.awt.Color(255, 255, 255));
        RadioGeneroColegioMixto1.setText("Mixto");
        Filtrador.add(RadioGeneroColegioMixto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 880, -1, -1));

        ColegioGeneroGrupo.add(RadioGeneroColegioFemenino);
        RadioGeneroColegioFemenino.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        RadioGeneroColegioFemenino.setForeground(new java.awt.Color(255, 255, 255));
        RadioGeneroColegioFemenino.setText("Femenino");
        Filtrador.add(RadioGeneroColegioFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 930, -1, -1));

        ColegioGeneroGrupo.add(RadioGeneroColegioMasculino);
        RadioGeneroColegioMasculino.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        RadioGeneroColegioMasculino.setForeground(new java.awt.Color(255, 255, 255));
        RadioGeneroColegioMasculino.setText("Masculino");
        Filtrador.add(RadioGeneroColegioMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 980, -1, -1));

        AreaColegio.add(RadioTodosArea);
        RadioTodosArea.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        RadioTodosArea.setForeground(new java.awt.Color(255, 255, 255));
        RadioTodosArea.setText("Todos");
        Filtrador.add(RadioTodosArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1260, -1, -1));

        AreaColegio.add(RadioRural);
        RadioRural.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        RadioRural.setForeground(new java.awt.Color(255, 255, 255));
        RadioRural.setText("Rural");
        Filtrador.add(RadioRural, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1160, -1, -1));

        AreaColegio.add(RadioUrbana);
        RadioUrbana.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        RadioUrbana.setForeground(new java.awt.Color(255, 255, 255));
        RadioUrbana.setText("Urbana");
        Filtrador.add(RadioUrbana, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1210, -1, -1));
        Filtrador.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1090, 260, 10));

        Plectura1.setMajorTickSpacing(10); // Espaciado entre las marcas principales
        Plectura1.setPaintTicks(true); // Dibuja las marcas
        Plectura1.setPaintLabels(true);
        Plectura1.setValue(0);

        Plectura1.setMajorTickSpacing(10);
        Plectura1.setBackground(new java.awt.Color(255, 102, 0));
        Plectura1.setForeground(new java.awt.Color(255, 255, 255));
        Filtrador.add(Plectura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1860, 250, -1));

        Plectura3.setMajorTickSpacing(10); // Espaciado entre las marcas principales
        Plectura3.setPaintTicks(true); // Dibuja las marcas
        Plectura3.setPaintLabels(true);
        Plectura3.setValue(0);

        Plectura3.setMajorTickSpacing(10);
        Plectura3.setBackground(new java.awt.Color(255, 102, 0));
        Plectura3.setForeground(new java.awt.Color(255, 255, 255));
        Filtrador.add(Plectura3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 3910, 250, -1));

        Plectura4.setMajorTickSpacing(10); // Espaciado entre las marcas principales
        Plectura4.setPaintTicks(true); // Dibuja las marcas
        Plectura4.setPaintLabels(true);
        Plectura4.setValue(0);

        Plectura4.setMajorTickSpacing(10);
        Plectura4.setBackground(new java.awt.Color(255, 102, 0));
        Plectura4.setForeground(new java.awt.Color(255, 255, 255));
        Filtrador.add(Plectura4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 2730, 250, -1));

        Plectura5.setMajorTickSpacing(10); // Espaciado entre las marcas principales
        Plectura5.setPaintTicks(true); // Dibuja las marcas
        Plectura5.setPaintLabels(true);
        Plectura5.setValue(0);

        Plectura5.setMajorTickSpacing(10);
        Plectura5.setBackground(new java.awt.Color(255, 102, 0));
        Plectura5.setForeground(new java.awt.Color(255, 255, 255));
        Filtrador.add(Plectura5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 3180, 250, -1));

        putajeglobalbarra.setMajorTickSpacing(500); // Espaciado entre las marcas principales
        putajeglobalbarra.setPaintTicks(true); // Dibuja las marcas
        putajeglobalbarra.setPaintLabels(true);
        putajeglobalbarra.setValue(0);

        putajeglobalbarra.setMajorTickSpacing(10);
        putajeglobalbarra.setBackground(new java.awt.Color(255, 102, 0));
        putajeglobalbarra.setForeground(new java.awt.Color(255, 255, 255));
        putajeglobalbarra.setEnabled(false);
        Filtrador.add(putajeglobalbarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 3700, 250, -1));

        Estractoselect.setBackground(new java.awt.Color(0, 102, 102));
        Estractoselect.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Estractoselect.setForeground(new java.awt.Color(255, 102, 0));
        Estractoselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 1", " 2", " 3", " 4", "5", "6", "7", "8", "9", "10" }));
        Filtrador.add(Estractoselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1600, 180, 50));

        desempeñolectura1.setBackground(new java.awt.Color(0, 102, 102));
        desempeñolectura1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        desempeñolectura1.setForeground(new java.awt.Color(255, 102, 0));
        desempeñolectura1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 1", " 2", " 3", " 4" }));
        Filtrador.add(desempeñolectura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2040, 180, 50));

        desempeñomatematica1.setBackground(new java.awt.Color(0, 102, 102));
        desempeñomatematica1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        desempeñomatematica1.setForeground(new java.awt.Color(255, 102, 0));
        desempeñomatematica1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 1", " 2", " 3", " 4" }));
        Filtrador.add(desempeñomatematica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2500, 180, 50));

        desempeñonaturales1.setBackground(new java.awt.Color(0, 102, 102));
        desempeñonaturales1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        desempeñonaturales1.setForeground(new java.awt.Color(255, 102, 0));
        desempeñonaturales1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 1", " 2", " 3", " 4" }));
        Filtrador.add(desempeñonaturales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 2930, 180, 50));

        PuntajeGlobal.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        PuntajeGlobal.setModel(new javax.swing.SpinnerNumberModel(1, 1, 500, 1));
        PuntajeGlobal.setToolTipText("");
        Filtrador.add(PuntajeGlobal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 3760, 70, 40));

        CamPG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/apagar (1).png"))); // NOI18N
        CamPG.setContentAreaFilled(false);
        CamPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamPGActionPerformed(evt);
            }
        });
        Filtrador.add(CamPG, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 3763, 40, 40));

        Filtr.setViewportView(Filtrador);

        jPanel1.add(Filtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -18, 340, 640));

        Info.setBackground(new java.awt.Color(255, 255, 255));
        Info.setForeground(new java.awt.Color(255, 255, 255));
        Info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, -10, 730, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Barra1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra1MousePressed
        mousex=evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_Barra1MousePressed

    private void Barra1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-mousex, y-mousey);
    }//GEN-LAST:event_Barra1MouseDragged

    
    private void SalirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBotonActionPerformed
     System.exit(0);
    }//GEN-LAST:event_SalirBotonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void año2020ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_año2020ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_año2020ActionPerformed

    private void MasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MasculinoActionPerformed

    private void año2019ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_año2019ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_año2019ActionPerformed

    private void año2018ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_año2018ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_año2018ActionPerformed

    private void CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaActionPerformed

    private void NoconozcomisgenitalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoconozcomisgenitalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoconozcomisgenitalesActionPerformed

    private void TarjetaIdentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarjetaIdentidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TarjetaIdentidadActionPerformed

    private void FemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemeninoActionPerformed

    private void AreaTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaTodosActionPerformed

    private void todosañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todosañoActionPerformed

    private void TodosTipodeDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodosTipodeDocumentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TodosTipodeDocumentosActionPerformed

    private void TodosGenerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodosGenerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TodosGenerosActionPerformed

    private void ColegiogeneroMIXTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColegiogeneroMIXTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColegiogeneroMIXTOActionPerformed

    private void ColegiogeneroFEMENINOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColegiogeneroFEMENINOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColegiogeneroFEMENINOActionPerformed

    private void ColegiogeneroMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColegiogeneroMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColegiogeneroMasculinoActionPerformed

    private void ColegiogeneroTODOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColegiogeneroTODOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColegiogeneroTODOSActionPerformed

    private void AreaRuralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaRuralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaRuralActionPerformed

    private void AreaUrbanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaUrbanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaUrbanaActionPerformed

    private void modoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoActionPerformed
 
        if (modo.isSelected()) {
           ImageIcon img = new ImageIcon(getClass().getResource("/imagenes/encender.png"));
        modo.setIcon(img);
        modo.setVerticalTextPosition(SwingConstants.BOTTOM);
        modo.setHorizontalTextPosition(SwingConstants.CENTER); 
        modo.setText("<html><center><font face='Century Gothic' size = '4' color='white'><b>Unica opcion");
        Labuenaaños();
   
       
        } else {
             ImageIcon img = new ImageIcon(getClass().getResource("/imagenes/apagar.png"));
        modo.setIcon(img);
           modo.setVerticalTextPosition(SwingConstants.BOTTOM);
        modo.setHorizontalTextPosition(SwingConstants.CENTER); 
        modo.setText("<html><center><font face='Century Gothic' size = '4' color='white'><b>Varias opciones");
        Lamalaaños();
 
        }
    }//GEN-LAST:event_modoActionPerformed

    private void radioañostodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioañostodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioañostodosActionPerformed

    private void BuscarGeneroColegioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarGeneroColegioActionPerformed
               
        if (modo.isSelected()) {
          
            if (RadioGeneroColegioMasculino.isSelected()) {
                obj2.setRadiocolmasculino();
                JOptionPane.showMessageDialog(null, obj2.getRadiocolmasculino());
            }
             if (RadioGeneroColegioMixto1.isSelected()) {
                 obj2.setRadiomixto();
                JOptionPane.showMessageDialog(null, obj2.getRadiomixto());
            }
              if (RadioGeneroColegioFemenino.isSelected()) {
                obj2.setRadiocolfemenino();
                JOptionPane.showMessageDialog(null, obj2.getRadiocolfemenino());
            }
               if (RadioGeneroColegioTodos.isSelected()) {
                 obj2.setRadiocoltodos();
                JOptionPane.showMessageDialog(null, obj2.getRadiocoltodos());
            }
            
        } else {
          
            if (ColegiogeneroMasculino.isSelected()) {
      
            obj.setColmasculino();
            System.out.println(obj.getColmasculino());
            
        }  if (ColegiogeneroFEMENINO.isSelected()) {
          
           obj.setColfemenino();
           System.out.println(obj.getColfemenino());
            
        }  if (ColegiogeneroTODOS.isSelected()) {
            obj.setColtodos();
           System.out.println(obj.getColtodos());
            
        }  if (ColegiogeneroMIXTO.isSelected()) {
            obj.setMixto();
           System.out.println(obj.getMixto());
            
        }  
        }

    }//GEN-LAST:event_BuscarGeneroColegioActionPerformed

    private void BotonGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGeneroActionPerformed
       
        if (modo.isSelected()) {
          
            if (RadioMasculino1.isSelected()) {
                obj2.setRadiomasculino();
                JOptionPane.showMessageDialog(null, obj2.getRadiomasculino());
            }
             if (RadioFemenino1.isSelected()) {
                 obj2.setRadiofemenino();
                JOptionPane.showMessageDialog(null, obj2.getRadiofemenino());
            }
              if (RadioNoidentificadoporningungenero1.isSelected()) {
                obj2.setRadionoidentificado();
                JOptionPane.showMessageDialog(null, obj2.getRadionoidentificado());
            }
               if (RadioTodosGeneros.isSelected()) {
                 obj2.setRadiotodoslosgeneros();
                JOptionPane.showMessageDialog(null, obj2.getRadiotodoslosgeneros());
            }
            
        } else {
          
            if (Masculino.isSelected()) {
      
            obj.setHombres();
            System.out.println(obj.getHombres());
            
        }  if (Femenino.isSelected()) {
          
           obj.setMujeres();
           System.out.println(obj.getMujeres());
            
        }  if (Noconozcomisgenitales.isSelected()) {
            obj.setNoidentificados();
           System.out.println(obj.getNoidentificados());
            
        }  if (TodosGeneros.isSelected()) {
             obj.setTodo();
           System.out.println(obj.getTodo());
            
        }
        }
        
        
    }//GEN-LAST:event_BotonGeneroActionPerformed

    private void BusquedaAñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaAñosActionPerformed
        
        if (modo.isSelected()) {
          
            if (radioaño2020.isSelected()) {
                obj2.setRadioaño2020();
                JOptionPane.showMessageDialog(null, obj2.getRadioaño2020());
            }
             if (radioaño2019.isSelected()) {
                 obj2.setRadioaño2019();
                JOptionPane.showMessageDialog(null, obj2.getRadioaño2019());
            }
              if (radioaño2018.isSelected()) {
                obj2.setRadioaño2018();
                JOptionPane.showMessageDialog(null, obj2.getRadioaño2018());
            }
               if (radioañostodos.isSelected()) {
                 obj2.setRadiotodosaños();
                JOptionPane.showMessageDialog(null, obj2.getRadiotodosaños());
            }
            
        } else {
          
            if (año2020.isSelected()) {
                obj.setAño2020();
            System.out.println(obj.getAño2020());
            
        }  if (año2019.isSelected()) {
          
           obj.setAño2019();
           System.out.println(obj.getAño2019());
            
        }  if (año2018.isSelected()) {
            obj.setAño2018();
           System.out.println(obj.getAño2018());
            
        }  if (todosaño.isSelected()) {
             obj.setTodosaños();
           System.out.println(obj.getTodosaños());
            
        }
        }
    }//GEN-LAST:event_BusquedaAñosActionPerformed

    private void BusquedatipodocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedatipodocumentoActionPerformed
     
                
        if (modo.isSelected()) {
          
            if (Radiodocumentocedula.isSelected()) {
                obj2.setRadiocedula();
                JOptionPane.showMessageDialog(null, obj2.getRadiocedula());
            }
             if (RadiodocumentoID1.isSelected()) {
                 obj2.setRadioid();
                JOptionPane.showMessageDialog(null, obj2.getRadioid());
            }
              if (RadiodocumentoTodos.isSelected()) {
                obj2.setTodosid();
                JOptionPane.showMessageDialog(null, obj2.getTodosid());
            }
           
            
        } else {
          
            if (Cedula.isSelected()) {
                obj.setCedula();
            System.out.println(obj.getCedula());
            
        }  if (TarjetaIdentidad.isSelected()) {
          
           obj.setID();
           System.out.println(obj.getID());
            
        }  if (TodosTipodeDocumentos.isSelected()) {
            obj.setIDtodos();
           System.out.println(obj.getIDtodos());
            
        } 
        }

        
        
    }//GEN-LAST:event_BusquedatipodocumentoActionPerformed

    private void BuscarAreaColegioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarAreaColegioActionPerformed
           
        if (modo.isSelected()) {
          
            if (RadioRural.isSelected()) {
                obj2.setRadiorural();
                JOptionPane.showMessageDialog(null, obj2.getRadiorural());
            }
             if (RadioUrbana.isSelected()) {
                 obj2.setRadiourbano();
                JOptionPane.showMessageDialog(null, obj2.getRadiourbano());
            }
              if (RadioTodosArea.isSelected()) {
                obj2.setRadiotodosarea();
                JOptionPane.showMessageDialog(null, obj2.getRadiotodosarea());
            }
            
        } else {
          
            if (AreaRural.isSelected()) {
      
            obj.setRural();
            System.out.println(obj.getRural());
            
        }  if (AreaTodos.isSelected()) {
          
           obj.setZonatodos();
           System.out.println(obj.getZonatodos());
            
        }  if (AreaUrbana.isSelected()) {
            obj.setUrbana();
           System.out.println(obj.getUrbana());
            
        } 
        }      
    }//GEN-LAST:event_BuscarAreaColegioActionPerformed

    private void BuscarDesempeñolecturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarDesempeñolecturaActionPerformed
        String select =(String) desempeñolectura1.getSelectedItem();
        JOptionPane.showMessageDialog(null, select);
    }//GEN-LAST:event_BuscarDesempeñolecturaActionPerformed

    private void MunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MunicipioActionPerformed
       String busquedamunicipios = (String) municipiosselec.getSelectedItem();
       JOptionPane.showMessageDialog(null, busquedamunicipios);
    }//GEN-LAST:event_MunicipioActionPerformed

    private void Busqueda15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Busqueda15ActionPerformed
       String select = (String) Estractoselect.getSelectedItem();
       JOptionPane.showMessageDialog(null, select);
    }//GEN-LAST:event_Busqueda15ActionPerformed

    private void Busqueda21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Busqueda21ActionPerformed
      String select = (String) desempeñomatematica1.getSelectedItem();
      JOptionPane.showMessageDialog(null, select);
    }//GEN-LAST:event_Busqueda21ActionPerformed

    private void Busqueda16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Busqueda16ActionPerformed
           String select = (String) desempeñonaturales1.getSelectedItem();
      JOptionPane.showMessageDialog(null, select);
    }//GEN-LAST:event_Busqueda16ActionPerformed

    private void Busqueda23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Busqueda23ActionPerformed
           String select = (String) desempeñoingles.getSelectedItem();
      JOptionPane.showMessageDialog(null, select);
    }//GEN-LAST:event_Busqueda23ActionPerformed

    private void CamPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamPGActionPerformed

        if (CamPG.isSelected()) {
           ImageIcon img = new ImageIcon(getClass().getResource("/imagenes/encender (1).png"));
        CamPG.setIcon(img);
        PuntajeGlobal.setEnabled(false);
        putajeglobalbarra.setEnabled(true);
     
        } else {
             ImageIcon img = new ImageIcon(getClass().getResource("/imagenes/apagar (1).png"));
        CamPG.setIcon(img);
           PuntajeGlobal.setEnabled(true);
        putajeglobalbarra.setEnabled(false);
 
        }       
        
        
    }//GEN-LAST:event_CamPGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AreaColegio;
    private javax.swing.JCheckBox AreaRural;
    private javax.swing.JCheckBox AreaTodos;
    private javax.swing.JCheckBox AreaUrbana;
    private javax.swing.JPanel Barra1;
    private javax.swing.JButton BotonGenero;
    private javax.swing.JButton BuscarAreaColegio;
    private javax.swing.JButton BuscarDesempeñolectura;
    private javax.swing.JButton BuscarGeneroColegio;
    private javax.swing.JButton Busqueda10;
    private javax.swing.JButton Busqueda14;
    private javax.swing.JButton Busqueda15;
    private javax.swing.JButton Busqueda16;
    private javax.swing.JButton Busqueda17;
    private javax.swing.JButton Busqueda18;
    private javax.swing.JButton Busqueda19;
    private javax.swing.JButton Busqueda21;
    private javax.swing.JButton Busqueda22;
    private javax.swing.JButton Busqueda23;
    private javax.swing.JButton BusquedaAños;
    private javax.swing.JButton Busquedatipodocumento;
    private javax.swing.JToggleButton CamPG;
    private javax.swing.JCheckBox Cedula;
    private javax.swing.ButtonGroup ColegioGeneroGrupo;
    private javax.swing.JCheckBox ColegiogeneroFEMENINO;
    private javax.swing.JCheckBox ColegiogeneroMIXTO;
    private javax.swing.JCheckBox ColegiogeneroMasculino;
    private javax.swing.JCheckBox ColegiogeneroTODOS;
    private javax.swing.JComboBox<String> Estractoselect;
    protected javax.swing.JCheckBox Femenino;
    private javax.swing.JScrollPane Filtr;
    private javax.swing.JPanel Filtrador;
    private javax.swing.ButtonGroup Generos;
    private javax.swing.ButtonGroup ID;
    private javax.swing.JPanel Info;
    protected javax.swing.JCheckBox Masculino;
    private javax.swing.JButton Municipio;
    protected javax.swing.JCheckBox Noconozcomisgenitales;
    private javax.swing.JSlider Plectura;
    private javax.swing.JSlider Plectura1;
    private javax.swing.JSlider Plectura3;
    private javax.swing.JSlider Plectura4;
    private javax.swing.JSlider Plectura5;
    private javax.swing.JSpinner PuntajeGlobal;
    private javax.swing.JRadioButton RadioFemenino1;
    private javax.swing.JRadioButton RadioGeneroColegioFemenino;
    private javax.swing.JRadioButton RadioGeneroColegioMasculino;
    private javax.swing.JRadioButton RadioGeneroColegioMixto1;
    private javax.swing.JRadioButton RadioGeneroColegioTodos;
    private javax.swing.JRadioButton RadioMasculino1;
    private javax.swing.JRadioButton RadioNoidentificadoporningungenero1;
    private javax.swing.JRadioButton RadioRural;
    private javax.swing.JRadioButton RadioTodosArea;
    private javax.swing.JRadioButton RadioTodosGeneros;
    private javax.swing.JRadioButton RadioUrbana;
    private javax.swing.JRadioButton RadiodocumentoID1;
    private javax.swing.JRadioButton RadiodocumentoTodos;
    private javax.swing.JRadioButton Radiodocumentocedula;
    private javax.swing.JButton SalirBoton;
    private javax.swing.JCheckBox TarjetaIdentidad;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    protected javax.swing.JCheckBox TodosGeneros;
    private javax.swing.JCheckBox TodosTipodeDocumentos;
    public javax.swing.JCheckBox año2018;
    public javax.swing.JCheckBox año2019;
    public javax.swing.JCheckBox año2020;
    private javax.swing.JComboBox<String> desempeñoingles;
    private javax.swing.JComboBox<String> desempeñolectura1;
    private javax.swing.JComboBox<String> desempeñomatematica1;
    private javax.swing.JComboBox<String> desempeñonaturales1;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.ButtonGroup grupoAños;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JToggleButton modo;
    private javax.swing.JComboBox<String> municipiosselec;
    private javax.swing.JSlider putajeglobalbarra;
    protected javax.swing.JRadioButton radioaño2018;
    protected javax.swing.JRadioButton radioaño2019;
    protected javax.swing.JRadioButton radioaño2020;
    public javax.swing.JRadioButton radioañostodos;
    protected javax.swing.JCheckBox todosaño;
    // End of variables declaration//GEN-END:variables
public  void  grafica_barras_1(){
    
    
       
       
        int datox=5;
        int datoy=10;
        int datoz=30;
        DefaultCategoryDataset datos = new DefaultCategoryDataset();
        datos.setValue(datox, "dato x", "nose x");
        datos.setValue(datoy, "dato x", "nose y");
         datos.setValue(datoz, "dato x", "nose z");
        

        JFreeChart grafico_1 = ChartFactory.createBarChart3D(
     "grafico 1",         //nombre del grafico
          "Datos x",      //nombre de las barras o columnas
         "resultados x",  //nombre de la numeracion
         datos,           //nombre de grafico
         PlotOrientation.HORIZONTAL,       //orientacion
         true,            //legenda de barras individuales por color
         true,          //url del grafico
         false
        );
        
        ChartPanel barras = new ChartPanel(grafico_1);
        barras.setMouseWheelEnabled(true);
        barras.setPreferredSize(new Dimension(0,300));
        barras.setLocation(0, 0);
    
       
        pack();
        repaint();
}

public void Labuenaaños(){
    
    //AÑOS
  
        radioaño2020.setVisible(true);
        radioaño2019.setVisible(true);
        radioaño2018.setVisible(true);
        radioañostodos.setVisible(true);

        año2020.setVisible(false);  
        año2019.setVisible(false);        
       año2018.setVisible(false);  
       todosaño.setVisible(false);
       
       //TIPO DE DOCUMENTO
       
       RadiodocumentoID1.setVisible(true);
              RadiodocumentoTodos.setVisible(true);
       Radiodocumentocedula.setVisible(true);

       
       
       Cedula.setVisible(false);
       TarjetaIdentidad.setVisible(false);
       TodosTipodeDocumentos.setVisible(false);
       
       //TIPO DE GENERO 
       
       Masculino.setVisible(false);
       Femenino.setVisible(false);
       Noconozcomisgenitales.setVisible(false);
       TodosGeneros.setVisible(false);
       
       RadioFemenino1.setVisible(true);
       RadioMasculino1.setVisible(true);
       RadioNoidentificadoporningungenero1.setVisible(true);
       RadioTodosGeneros.setVisible(true);
       
       //GENERO DEL COLEGIO (OCULTAR CAJAS)
       ColegiogeneroFEMENINO.setVisible(false);
       ColegiogeneroMIXTO.setVisible(false);
       ColegiogeneroMasculino.setVisible(false);
       ColegiogeneroTODOS.setVisible(false);
       
       RadioGeneroColegioFemenino.setVisible(true);
       RadioGeneroColegioMasculino.setVisible(true);
       RadioGeneroColegioMixto1.setVisible(true);
       RadioGeneroColegioTodos.setVisible(true);
       
       //AREA (OCULTAR CAJAS)
       
       AreaRural.setVisible(false);
       AreaUrbana.setVisible(false);
       AreaTodos.setVisible(false);
       
              RadioRural.setVisible(true);
       RadioUrbana.setVisible(true);
       RadioTodosArea.setVisible(true);
      
       
       
        }
        
        public void Lamalaaños(){
            //AÑOS
        radioañostodos.setVisible(false);
        radioaño2020.setVisible(false);
         radioaño2019.setVisible(false);
         radioaño2018.setVisible(false);
         
         año2020.setVisible(true);  
         año2019.setVisible(true);  
         año2018.setVisible(true);  
         todosaño.setVisible(true);
         
         //TIPO DE DOCUMEMTNO
         
           Cedula.setVisible(true);
       TarjetaIdentidad.setVisible(true);
       TodosTipodeDocumentos.setVisible(true);
            
        RadiodocumentoID1.setVisible(false);
              RadiodocumentoTodos.setVisible(false);
       Radiodocumentocedula.setVisible(false);
       
       //GENERO
           RadioFemenino1.setVisible(false);
       RadioMasculino1.setVisible(false);
       RadioNoidentificadoporningungenero1.setVisible(false);
       RadioTodosGeneros.setVisible(false);
       
       Masculino.setVisible(true);
       Femenino.setVisible(true);
       Noconozcomisgenitales.setVisible(true);
       TodosGeneros.setVisible(true);
       
       //COLEGIO GENERO (MOSTRAR CAJAS DE TEXTO)
        ColegiogeneroFEMENINO.setVisible(true);
       ColegiogeneroMIXTO.setVisible(true);
       ColegiogeneroMasculino.setVisible(true);
       ColegiogeneroTODOS.setVisible(true);
       
         RadioGeneroColegioFemenino.setVisible(false);
       RadioGeneroColegioMasculino.setVisible(false);
       RadioGeneroColegioMixto1.setVisible(false);
       RadioGeneroColegioTodos.setVisible(false);
       
       //AREA (MOSTRAR CAJAS)
       
        AreaRural.setVisible(true);
       AreaUrbana.setVisible(true);
       AreaTodos.setVisible(true);
       
       RadioRural.setVisible(false);
       RadioUrbana.setVisible(false);
       RadioTodosArea.setVisible(false);
            
        }
        
        

}

