/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.awt.Color;



public class libro extends javax.swing.JFrame {

    int mousex, mousey;
    
    public libro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pag1 = new javax.swing.JPanel();
        pagina_actual_1 = new javax.swing.JLabel();
        pag2 = new javax.swing.JPanel();
        pagina_actual_2 = new javax.swing.JLabel();
        pag3 = new javax.swing.JPanel();
        pagina_actual_3 = new javax.swing.JLabel();
        pag4 = new javax.swing.JPanel();
        pagina_actual_4 = new javax.swing.JLabel();
        pag5 = new javax.swing.JPanel();
        pagina_actual_5 = new javax.swing.JLabel();
        pag6 = new javax.swing.JPanel();
        pagina_actual_6 = new javax.swing.JLabel();
        eleccion_1 = new javax.swing.JPanel();
        vinculo_1 = new javax.swing.JLabel();
        eleccion_2 = new javax.swing.JPanel();
        vinculo_2 = new javax.swing.JLabel();
        eleccion_3 = new javax.swing.JPanel();
        vinculo_3 = new javax.swing.JLabel();
        eleccion_4 = new javax.swing.JPanel();
        vinculo_4 = new javax.swing.JLabel();
        eleccion_5 = new javax.swing.JPanel();
        vinculo_5 = new javax.swing.JLabel();
        eleccion_6 = new javax.swing.JPanel();
        vinculo_6 = new javax.swing.JLabel();
        jEditorPane1 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        xd = new javax.swing.JLabel();
        textobasura8 = new javax.swing.JLabel();
        texto4 = new javax.swing.JLabel();
        texto5 = new javax.swing.JLabel();
        textobasura9 = new javax.swing.JLabel();
        texto6 = new javax.swing.JLabel();
        jButton1 = new MiBoton();
        P_siguiente_1 = new javax.swing.JPanel();
        siguiente_1 = new javax.swing.JLabel();
        P_siguiente_2 = new javax.swing.JPanel();
        siguiente_2 = new javax.swing.JLabel();
        P_siguiente_3 = new javax.swing.JPanel();
        siguiente_3 = new javax.swing.JLabel();
        P_siguiente_4 = new javax.swing.JPanel();
        siguiente_4 = new javax.swing.JLabel();
        P_siguiente_5 = new javax.swing.JPanel();
        siguiente_5 = new javax.swing.JLabel();
        P_regresar_1 = new javax.swing.JPanel();
        regreso_1 = new javax.swing.JLabel();
        P_regresar_2 = new javax.swing.JPanel();
        regreso_2 = new javax.swing.JLabel();
        P_regresar_3 = new javax.swing.JPanel();
        regreso_3 = new javax.swing.JLabel();
        P_regresar_4 = new javax.swing.JPanel();
        regreso_4 = new javax.swing.JLabel();
        P_regresar_5 = new javax.swing.JPanel();
        regreso_5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(91, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(580, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(580, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pag1.setBackground(new java.awt.Color(204, 255, 255));
        pag1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pagina_actual_1.setBackground(new java.awt.Color(204, 204, 255));
        pagina_actual_1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pagina_actual_1.setForeground(new java.awt.Color(0, 0, 204));
        pagina_actual_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pagina_actual_1.setText("1");

        javax.swing.GroupLayout pag1Layout = new javax.swing.GroupLayout(pag1);
        pag1.setLayout(pag1Layout);
        pag1Layout.setHorizontalGroup(
            pag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagina_actual_1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pag1Layout.setVerticalGroup(
            pag1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagina_actual_1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        pagina_actual_1.setVisible(true);

        jPanel1.add(pag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, 40, 40));
        pag1.setVisible(true);

        pag2.setBackground(new java.awt.Color(204, 255, 255));
        pag2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pagina_actual_2.setBackground(new java.awt.Color(204, 204, 255));
        pagina_actual_2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pagina_actual_2.setForeground(new java.awt.Color(0, 0, 204));
        pagina_actual_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pagina_actual_2.setText("2");

        javax.swing.GroupLayout pag2Layout = new javax.swing.GroupLayout(pag2);
        pag2.setLayout(pag2Layout);
        pag2Layout.setHorizontalGroup(
            pag2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagina_actual_2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pag2Layout.setVerticalGroup(
            pag2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagina_actual_2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(pag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, 40, 40));
        pagina_actual_2.setVisible(false);

        pag3.setBackground(new java.awt.Color(204, 255, 255));
        pag3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pagina_actual_3.setBackground(new java.awt.Color(204, 204, 255));
        pagina_actual_3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pagina_actual_3.setForeground(new java.awt.Color(0, 0, 204));
        pagina_actual_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pagina_actual_3.setText("3");

        javax.swing.GroupLayout pag3Layout = new javax.swing.GroupLayout(pag3);
        pag3.setLayout(pag3Layout);
        pag3Layout.setHorizontalGroup(
            pag3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagina_actual_3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pag3Layout.setVerticalGroup(
            pag3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagina_actual_3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(pag3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, 40, 40));
        pagina_actual_3.setVisible(false);

        pag4.setBackground(new java.awt.Color(204, 255, 255));
        pag4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pagina_actual_4.setBackground(new java.awt.Color(204, 204, 255));
        pagina_actual_4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pagina_actual_4.setForeground(new java.awt.Color(0, 0, 204));
        pagina_actual_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pagina_actual_4.setText("4");

        javax.swing.GroupLayout pag4Layout = new javax.swing.GroupLayout(pag4);
        pag4.setLayout(pag4Layout);
        pag4Layout.setHorizontalGroup(
            pag4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagina_actual_4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pag4Layout.setVerticalGroup(
            pag4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagina_actual_4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(pag4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, 40, 40));
        pagina_actual_4.setVisible(false);

        pag5.setBackground(new java.awt.Color(204, 255, 255));
        pag5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pagina_actual_5.setBackground(new java.awt.Color(204, 204, 255));
        pagina_actual_5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pagina_actual_5.setForeground(new java.awt.Color(0, 0, 204));
        pagina_actual_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pagina_actual_5.setText("5");

        javax.swing.GroupLayout pag5Layout = new javax.swing.GroupLayout(pag5);
        pag5.setLayout(pag5Layout);
        pag5Layout.setHorizontalGroup(
            pag5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagina_actual_5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pag5Layout.setVerticalGroup(
            pag5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagina_actual_5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(pag5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, 40, 40));
        pagina_actual_5.setVisible(false);

        pag6.setBackground(new java.awt.Color(204, 255, 255));
        pag6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pagina_actual_6.setBackground(new java.awt.Color(204, 204, 255));
        pagina_actual_6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pagina_actual_6.setForeground(new java.awt.Color(0, 0, 204));
        pagina_actual_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pagina_actual_6.setText("6");

        javax.swing.GroupLayout pag6Layout = new javax.swing.GroupLayout(pag6);
        pag6.setLayout(pag6Layout);
        pag6Layout.setHorizontalGroup(
            pag6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagina_actual_6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pag6Layout.setVerticalGroup(
            pag6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pagina_actual_6, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(pag6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, 40, 40));
        pagina_actual_6.setVisible(false);

        eleccion_1.setBackground(new java.awt.Color(255, 255, 255));
        eleccion_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        eleccion_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eleccion_1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eleccion_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eleccion_1MouseExited(evt);
            }
        });

        vinculo_1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vinculo_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vinculo_1.setText("1");

        javax.swing.GroupLayout eleccion_1Layout = new javax.swing.GroupLayout(eleccion_1);
        eleccion_1.setLayout(eleccion_1Layout);
        eleccion_1Layout.setHorizontalGroup(
            eleccion_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vinculo_1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        eleccion_1Layout.setVerticalGroup(
            eleccion_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vinculo_1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.add(eleccion_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 610, 30, 30));

        eleccion_2.setBackground(new java.awt.Color(255, 255, 255));
        eleccion_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        eleccion_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eleccion_2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eleccion_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eleccion_2MouseExited(evt);
            }
        });

        vinculo_2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vinculo_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vinculo_2.setText("2");

        javax.swing.GroupLayout eleccion_2Layout = new javax.swing.GroupLayout(eleccion_2);
        eleccion_2.setLayout(eleccion_2Layout);
        eleccion_2Layout.setHorizontalGroup(
            eleccion_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vinculo_2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        eleccion_2Layout.setVerticalGroup(
            eleccion_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vinculo_2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.add(eleccion_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 30, 30));

        eleccion_3.setBackground(new java.awt.Color(255, 255, 255));
        eleccion_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        eleccion_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eleccion_3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eleccion_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eleccion_3MouseExited(evt);
            }
        });

        vinculo_3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vinculo_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vinculo_3.setText("3");

        javax.swing.GroupLayout eleccion_3Layout = new javax.swing.GroupLayout(eleccion_3);
        eleccion_3.setLayout(eleccion_3Layout);
        eleccion_3Layout.setHorizontalGroup(
            eleccion_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vinculo_3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        eleccion_3Layout.setVerticalGroup(
            eleccion_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vinculo_3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.add(eleccion_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, 30, 30));

        eleccion_4.setBackground(new java.awt.Color(255, 255, 255));
        eleccion_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        eleccion_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eleccion_4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eleccion_4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eleccion_4MouseExited(evt);
            }
        });

        vinculo_4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vinculo_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vinculo_4.setText("4");

        javax.swing.GroupLayout eleccion_4Layout = new javax.swing.GroupLayout(eleccion_4);
        eleccion_4.setLayout(eleccion_4Layout);
        eleccion_4Layout.setHorizontalGroup(
            eleccion_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vinculo_4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        eleccion_4Layout.setVerticalGroup(
            eleccion_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vinculo_4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.add(eleccion_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 610, -1, -1));

        eleccion_5.setBackground(new java.awt.Color(255, 255, 255));
        eleccion_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        eleccion_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eleccion_5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eleccion_5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eleccion_5MouseExited(evt);
            }
        });

        vinculo_5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vinculo_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vinculo_5.setText("5");

        javax.swing.GroupLayout eleccion_5Layout = new javax.swing.GroupLayout(eleccion_5);
        eleccion_5.setLayout(eleccion_5Layout);
        eleccion_5Layout.setHorizontalGroup(
            eleccion_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vinculo_5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        eleccion_5Layout.setVerticalGroup(
            eleccion_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vinculo_5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.add(eleccion_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 610, -1, -1));

        eleccion_6.setBackground(new java.awt.Color(255, 255, 255));
        eleccion_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        eleccion_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eleccion_6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eleccion_6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eleccion_6MouseExited(evt);
            }
        });

        vinculo_6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vinculo_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vinculo_6.setText("6");

        javax.swing.GroupLayout eleccion_6Layout = new javax.swing.GroupLayout(eleccion_6);
        eleccion_6.setLayout(eleccion_6Layout);
        eleccion_6Layout.setHorizontalGroup(
            eleccion_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vinculo_6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        eleccion_6Layout.setVerticalGroup(
            eleccion_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vinculo_6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.add(eleccion_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 610, 30, 30));

        jEditorPane1.setBackground(new java.awt.Color(51, 0, 0));
        jEditorPane1.setFont(new java.awt.Font("Minecraft", 1, 14)); // NOI18N
        jEditorPane1.setForeground(new java.awt.Color(51, 0, 0));
        jEditorPane1.setText("<html>Que es EduCompu?<br><br>Es una aplicacion tipo dashboard que permite realizar<br>busquedas de varios tipos, estas <br> pueden ser fijas o compuestas, cada busqueda debe retornar un valor que se vera<br>representado en una grafica<br><br>En este caso todo esta relacionado con los resultados de las pruebas saber de los años 2018/2019/2020.<html>");
        jEditorPane1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jEditorPane1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jEditorPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 430, 450));
        jEditorPane1.setVisible(true);

        texto2.setBackground(new java.awt.Color(51, 0, 0));
        texto2.setFont(new java.awt.Font("Minecraft", 1, 14)); // NOI18N
        texto2.setForeground(new java.awt.Color(51, 0, 0));
        texto2.setText("<html><u><b>Boton de prendido y apagado</b></u><br><br>Comenzando por la parte de arriba tendremos un boton de apagado y encendido, estos seran sus unicos dos estados Cuando esta encendido tendremos activas las busquedas fijas en el panel de color azul aguamarina, y al lado izquierdo de la aplicacion, y al lado derecho, un panel de color blanco tendremos el apartado de las graficas donde veremos de forma grafica el resultado de nuestra busqueda<br><br><br>Al pasar de estado en estado nuestras consultas y graficas se reiniciaran haciendo que todo vuelva a su valor original (null) asi este boton tiene otra funcion que es la de refrescar las graficas y selecciones.");
        texto2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 430, 460));
        texto2.setVisible(false);

        texto3.setBackground(new java.awt.Color(51, 0, 0));
        texto3.setFont(new java.awt.Font("Minecraft", 1, 14)); // NOI18N
        texto3.setForeground(new java.awt.Color(51, 0, 0));
        texto3.setText("<html><u>Boton LIMPIAR general y LIMPIAR de busquedas fijas</u><br><br><br>Como el mismo dice, este se encarga de refrescar las graficas de las busquedas fijas, las primeras en las primeras <u>7</u> categorias de las busqueda fija existe un boton son simbolo de una brocha, este sirve para limpiar la seleccion junto con su representacion grafica en las tablas donde este aparece.</html>");
        texto3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(texto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 440, 440));
        texto3.setVisible(false);

        xd.setBackground(new java.awt.Color(255, 255, 255));
        xd.setFont(new java.awt.Font("Minecraft", 1, 18)); // NOI18N
        xd.setForeground(new java.awt.Color(0, 102, 102));
        xd.setText("Compu");
        jPanel1.add(xd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 80, 70));
        jEditorPane1.setVisible(true);

        textobasura8.setBackground(new java.awt.Color(51, 0, 0));
        textobasura8.setFont(new java.awt.Font("Minecraft", 1, 18)); // NOI18N
        textobasura8.setForeground(new java.awt.Color(51, 0, 0));
        textobasura8.setText("Como usar ");
        jPanel1.add(textobasura8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 150, 70));
        jEditorPane1.setVisible(true);

        texto4.setBackground(new java.awt.Color(51, 0, 0));
        texto4.setFont(new java.awt.Font("Minecraft", 1, 12)); // NOI18N
        texto4.setForeground(new java.awt.Color(51, 0, 0));
        texto4.setText("<html><u>Busquedas fijas activadas</u><br><br><br>Cuanto tengamos las busquedas compuestas activadas vamos a tener un total de <u>17</u> secciones separadas por titulos de color naranja, las 7 primeras corresponden a:<br>Año<br>Tipo de documento<br>Genero<br>Genero del colegio<br>Area del colegio<br>Estractp<br>Estas seran graficadas en la parte superior <u>(grafico de lineas)</u> y en la parte inferior izquiera<u> (grafico pastel)</u><br><br>Mientras que las secciones restantes seran graficadas en la parte inferior derecha, estas seran representadas por barra de porsentajes y estas tambien seran visibles tanto en las busquedas compuestas como en las busquedas fijas, estas secciones restantes todas representan puntajes de desempeño, los iconos que existen en esa seccion facilitaran la compresion de los graficos ya que si dejas el puntero del mouse encima de los iconos vas a saber que significa cada simbolo y que se hace en esa parte, existen porcentajes en esa seccion que nos indica el porcentaje de personas que tienen la nota solicitada.</html>");
        texto4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(texto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 430, 490));
        texto4.setVisible(false);

        texto5.setBackground(new java.awt.Color(51, 0, 0));
        texto5.setFont(new java.awt.Font("Minecraft", 1, 12)); // NOI18N
        texto5.setForeground(new java.awt.Color(51, 0, 0));
        texto5.setText("<html><u>Consultas fijas desactivadas</u><br><br><br>Al tener las consultar fijas desactivadas vamos a tener acceso a las busquedas conpuestas, esto afecta a las primeras 7 secciones de nuesta area de busquedas, cambiando los radiobuttons a checkbox, ocacionando que pueda realizar multiples selecciones, al pasar a este estados tambien se nos cambiara nuestra area de graficos, desaparecera el grafico de barras y el grafico pastel y seran reemplazados por graficos de porcentaje, donde veremos los porsentajes separados por años, en este caso la app tiene registro de los años 2018/2019/2020<br><br>al filtrar busquedas compuestas podremos buscar de forma mas flexible informacion mas general, por ejemplo, mujeres en el año 2018 con calendario B, se nos graficara la cantidad de registros que se encontraron.<br><br><br>Ademas, ademas no se modificara el grafico de la parte inferior derecha ya que esa corresponde a los porsentajes de las demas busquedas, seran permanenetemente fijas y estas siempre se van a visualizar en los dos modos.<br><br>ADVERTENCIA: este modo todavia sigue en desarrollo asi que esta incompleto.<html>");
        texto5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(texto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 430, 480));
        texto5.setVisible(false);

        textobasura9.setBackground(new java.awt.Color(51, 0, 0));
        textobasura9.setFont(new java.awt.Font("Minecraft", 1, 18)); // NOI18N
        textobasura9.setForeground(new java.awt.Color(255, 102, 0));
        textobasura9.setText("Edu");
        jPanel1.add(textobasura9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 50, 70));
        jEditorPane1.setVisible(true);

        texto6.setBackground(new java.awt.Color(51, 0, 0));
        texto6.setFont(new java.awt.Font("Minecraft", 1, 18)); // NOI18N
        texto6.setForeground(new java.awt.Color(51, 0, 0));
        texto6.setText("<html>Eso es todo! disfruta de la aplicacion :D!<br><br><br><br><br>Desarrolladores:<br>Jolmer Viedma<br>Alejandro Hernandez<br>Adrian Saavedra</html>");
        texto6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(texto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 430, 450));
        texto6.setVisible(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida (1).png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 60, 30));

        P_siguiente_1.setBackground(new java.awt.Color(255, 255, 255));
        P_siguiente_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        P_siguiente_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P_siguiente_1_1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                P_siguiente_1_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                P_siguiente_1_1MouseExited(evt);
            }
        });

        siguiente_1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        siguiente_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        siguiente_1.setText("Siguiente");

        javax.swing.GroupLayout P_siguiente_1Layout = new javax.swing.GroupLayout(P_siguiente_1);
        P_siguiente_1.setLayout(P_siguiente_1Layout);
        P_siguiente_1Layout.setHorizontalGroup(
            P_siguiente_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_siguiente_1Layout.createSequentialGroup()
                .addComponent(siguiente_1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        P_siguiente_1Layout.setVerticalGroup(
            P_siguiente_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_siguiente_1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(siguiente_1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(P_siguiente_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 650, -1, 40));

        P_siguiente_2.setBackground(new java.awt.Color(255, 255, 255));
        P_siguiente_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        P_siguiente_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P_siguiente_2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                P_siguiente_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                P_siguiente_2MouseExited(evt);
            }
        });

        siguiente_2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        siguiente_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        siguiente_2.setText("Siguiente");

        javax.swing.GroupLayout P_siguiente_2Layout = new javax.swing.GroupLayout(P_siguiente_2);
        P_siguiente_2.setLayout(P_siguiente_2Layout);
        P_siguiente_2Layout.setHorizontalGroup(
            P_siguiente_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_siguiente_2Layout.createSequentialGroup()
                .addComponent(siguiente_2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        P_siguiente_2Layout.setVerticalGroup(
            P_siguiente_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_siguiente_2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(siguiente_2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(P_siguiente_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 650, -1, 40));

        P_siguiente_3.setBackground(new java.awt.Color(255, 255, 255));
        P_siguiente_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        P_siguiente_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P_siguiente_3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                P_siguiente_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                P_siguiente_3MouseExited(evt);
            }
        });

        siguiente_3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        siguiente_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        siguiente_3.setText("Siguiente");

        javax.swing.GroupLayout P_siguiente_3Layout = new javax.swing.GroupLayout(P_siguiente_3);
        P_siguiente_3.setLayout(P_siguiente_3Layout);
        P_siguiente_3Layout.setHorizontalGroup(
            P_siguiente_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_siguiente_3Layout.createSequentialGroup()
                .addComponent(siguiente_3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        P_siguiente_3Layout.setVerticalGroup(
            P_siguiente_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_siguiente_3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(siguiente_3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(P_siguiente_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 650, -1, 40));

        P_siguiente_4.setBackground(new java.awt.Color(255, 255, 255));
        P_siguiente_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        P_siguiente_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P_siguiente_4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                P_siguiente_4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                P_siguiente_4MouseExited(evt);
            }
        });

        siguiente_4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        siguiente_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        siguiente_4.setText("Siguiente");

        javax.swing.GroupLayout P_siguiente_4Layout = new javax.swing.GroupLayout(P_siguiente_4);
        P_siguiente_4.setLayout(P_siguiente_4Layout);
        P_siguiente_4Layout.setHorizontalGroup(
            P_siguiente_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_siguiente_4Layout.createSequentialGroup()
                .addComponent(siguiente_4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        P_siguiente_4Layout.setVerticalGroup(
            P_siguiente_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_siguiente_4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(siguiente_4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(P_siguiente_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 650, -1, 40));

        P_siguiente_5.setBackground(new java.awt.Color(255, 255, 255));
        P_siguiente_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        P_siguiente_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P_siguiente_5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                P_siguiente_5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                P_siguiente_5MouseExited(evt);
            }
        });

        siguiente_5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        siguiente_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        siguiente_5.setText("Siguiente");

        javax.swing.GroupLayout P_siguiente_5Layout = new javax.swing.GroupLayout(P_siguiente_5);
        P_siguiente_5.setLayout(P_siguiente_5Layout);
        P_siguiente_5Layout.setHorizontalGroup(
            P_siguiente_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_siguiente_5Layout.createSequentialGroup()
                .addComponent(siguiente_5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        P_siguiente_5Layout.setVerticalGroup(
            P_siguiente_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_siguiente_5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(siguiente_5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(P_siguiente_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 650, -1, 40));

        P_regresar_1.setBackground(new java.awt.Color(255, 255, 255));
        P_regresar_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        P_regresar_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                P_regresar_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                P_regresar_1MouseExited(evt);
            }
        });

        regreso_1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        regreso_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regreso_1.setText("Regresar");
        regreso_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regreso_1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout P_regresar_1Layout = new javax.swing.GroupLayout(P_regresar_1);
        P_regresar_1.setLayout(P_regresar_1Layout);
        P_regresar_1Layout.setHorizontalGroup(
            P_regresar_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regreso_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        P_regresar_1Layout.setVerticalGroup(
            P_regresar_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regreso_1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(P_regresar_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 650, 110, 40));
        P_regresar_1.setVisible(false);

        P_regresar_2.setBackground(new java.awt.Color(255, 255, 255));
        P_regresar_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        P_regresar_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                P_regresar_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                P_regresar_2MouseExited(evt);
            }
        });

        regreso_2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        regreso_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regreso_2.setText("Regresar");
        regreso_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regreso_2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout P_regresar_2Layout = new javax.swing.GroupLayout(P_regresar_2);
        P_regresar_2.setLayout(P_regresar_2Layout);
        P_regresar_2Layout.setHorizontalGroup(
            P_regresar_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regreso_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        P_regresar_2Layout.setVerticalGroup(
            P_regresar_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regreso_2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(P_regresar_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 650, 110, 40));
        P_regresar_2.setVisible(false);

        P_regresar_3.setBackground(new java.awt.Color(255, 255, 255));
        P_regresar_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        P_regresar_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                P_regresar_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                P_regresar_3MouseExited(evt);
            }
        });

        regreso_3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        regreso_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regreso_3.setText("Regresar");
        regreso_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regreso_3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout P_regresar_3Layout = new javax.swing.GroupLayout(P_regresar_3);
        P_regresar_3.setLayout(P_regresar_3Layout);
        P_regresar_3Layout.setHorizontalGroup(
            P_regresar_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regreso_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        P_regresar_3Layout.setVerticalGroup(
            P_regresar_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regreso_3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(P_regresar_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 650, 110, 40));
        P_regresar_3.setVisible(false);

        P_regresar_4.setBackground(new java.awt.Color(255, 255, 255));
        P_regresar_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        P_regresar_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                P_regresar_4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                P_regresar_4MouseExited(evt);
            }
        });

        regreso_4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        regreso_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regreso_4.setText("Regresar");
        regreso_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regreso_4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout P_regresar_4Layout = new javax.swing.GroupLayout(P_regresar_4);
        P_regresar_4.setLayout(P_regresar_4Layout);
        P_regresar_4Layout.setHorizontalGroup(
            P_regresar_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regreso_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        P_regresar_4Layout.setVerticalGroup(
            P_regresar_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regreso_4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(P_regresar_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 650, 110, 40));
        P_regresar_4.setVisible(false);

        P_regresar_5.setBackground(new java.awt.Color(255, 255, 255));
        P_regresar_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        P_regresar_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                P_regresar_5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                P_regresar_5MouseExited(evt);
            }
        });

        regreso_5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        regreso_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regreso_5.setText("Regresar");
        regreso_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regreso_5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout P_regresar_5Layout = new javax.swing.GroupLayout(P_regresar_5);
        P_regresar_5.setLayout(P_regresar_5Layout);
        P_regresar_5Layout.setHorizontalGroup(
            P_regresar_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regreso_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        P_regresar_5Layout.setVerticalGroup(
            P_regresar_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regreso_5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(P_regresar_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 650, 110, 40));
        P_regresar_5.setVisible(false);

        jButton2.setContentAreaFilled(false);
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jButton2MouseDragged(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VYPSF.png"))); // NOI18N
        fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                fondoMouseDragged(evt);
            }
        });
        fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fondoMousePressed(evt);
            }
        });
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -60, 670, 840));
        fondo.getAccessibleContext().setAccessibleName("siguiente pagina");

        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMousePressed
    
    }//GEN-LAST:event_fondoMousePressed

    private void fondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMouseDragged
          
    }//GEN-LAST:event_fondoMouseDragged

    private void P_siguiente_1_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_siguiente_1_1MouseClicked
        jEditorPane1.setVisible(false);
        texto2.setVisible(true);
        texto3.setVisible(false);
        texto4.setVisible(false);
        texto5.setVisible(false);
        texto6.setVisible(false);
        pag1.setVisible(false);
        pag2.setVisible(true);
        pag3.setVisible(false);
        pag4.setVisible(false);
        pag5.setVisible(false);
        pag6.setVisible(false);
        P_siguiente_1.setVisible(false);
        P_siguiente_2.setVisible(true);
        P_siguiente_3.setVisible(false);
        P_siguiente_4.setVisible(false);
        P_siguiente_5.setVisible(false);
        pagina_actual_1.setVisible(false);
        pagina_actual_2.setVisible(true);
        pagina_actual_3.setVisible(false);
        pagina_actual_4.setVisible(false);
        pagina_actual_5.setVisible(false);
        pagina_actual_6.setVisible(false);
        P_regresar_1.setVisible(true);
        P_regresar_2.setVisible(false);
        P_regresar_3.setVisible(false);
        P_regresar_4.setVisible(false);
        P_regresar_5.setVisible(false);
        
    }//GEN-LAST:event_P_siguiente_1_1MouseClicked

    private void P_siguiente_1_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_siguiente_1_1MouseEntered
        P_siguiente_1.setBackground(Color.gray);
        siguiente_1.setForeground(Color.white);
    }//GEN-LAST:event_P_siguiente_1_1MouseEntered

    private void P_siguiente_1_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_siguiente_1_1MouseExited
        P_siguiente_1.setBackground(Color.white);
        siguiente_1.setForeground(Color.black);
    }//GEN-LAST:event_P_siguiente_1_1MouseExited

    private void eleccion_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_1MouseEntered
        eleccion_1.setBackground(Color.orange);
        vinculo_1.setForeground(Color.black);
    }//GEN-LAST:event_eleccion_1MouseEntered

    private void eleccion_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_1MouseExited
        eleccion_1.setBackground(Color.white);
        vinculo_1.setForeground(Color.black);
    }//GEN-LAST:event_eleccion_1MouseExited

    private void eleccion_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_2MouseEntered
        eleccion_2.setBackground(Color.orange);
        vinculo_2.setForeground(Color.black);
    }//GEN-LAST:event_eleccion_2MouseEntered

    private void eleccion_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_2MouseExited
        eleccion_2.setBackground(Color.white);
        vinculo_2.setForeground(Color.black);
    }//GEN-LAST:event_eleccion_2MouseExited

    private void eleccion_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_3MouseEntered
        eleccion_3.setBackground(Color.orange);
        vinculo_3.setForeground(Color.black);
    }//GEN-LAST:event_eleccion_3MouseEntered

    private void eleccion_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_3MouseExited
        eleccion_3.setBackground(Color.white);
        vinculo_3.setForeground(Color.black);
    }//GEN-LAST:event_eleccion_3MouseExited

    private void eleccion_4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_4MouseEntered
        eleccion_4.setBackground(Color.orange);
        vinculo_4.setForeground(Color.black);
    }//GEN-LAST:event_eleccion_4MouseEntered

    private void eleccion_4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_4MouseExited
        eleccion_4.setBackground(Color.white);
        vinculo_4.setForeground(Color.black);
    }//GEN-LAST:event_eleccion_4MouseExited

    private void eleccion_5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_5MouseEntered
        eleccion_5.setBackground(Color.orange);
        vinculo_5.setForeground(Color.black);
    }//GEN-LAST:event_eleccion_5MouseEntered

    private void eleccion_5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_5MouseExited
        eleccion_5.setBackground(Color.white);
        vinculo_5.setForeground(Color.black);
    }//GEN-LAST:event_eleccion_5MouseExited

    private void eleccion_6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_6MouseEntered
        eleccion_6.setBackground(Color.orange);
        vinculo_6.setForeground(Color.black);
    }//GEN-LAST:event_eleccion_6MouseEntered

    private void eleccion_6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_6MouseExited
        eleccion_6.setBackground(Color.white);
        vinculo_6.setForeground(Color.black);
    }//GEN-LAST:event_eleccion_6MouseExited

    private void eleccion_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_1MouseClicked
        jEditorPane1.setVisible(true);
        texto2.setVisible(false);
        texto3.setVisible(false);
        texto4.setVisible(false);
        texto5.setVisible(false);
        texto6.setVisible(false);
        pag1.setVisible(true);
        pag2.setVisible(false);
        pag3.setVisible(false);
        pag4.setVisible(false);
        pag5.setVisible(false);
        pag6.setVisible(false);
        pagina_actual_1.setVisible(true);
        pagina_actual_2.setVisible(false);
        pagina_actual_3.setVisible(false);
        pagina_actual_4.setVisible(false);
        pagina_actual_5.setVisible(false);
        pagina_actual_6.setVisible(false);
        P_siguiente_1.setVisible(true);
        P_siguiente_2.setVisible(false);
        P_siguiente_3.setVisible(false);
        P_siguiente_4.setVisible(false);
        P_siguiente_5.setVisible(false);
        P_regresar_1.setVisible(false);
        P_regresar_2.setVisible(false);
        P_regresar_3.setVisible(false);
        P_regresar_4.setVisible(false);
        P_regresar_5.setVisible(false);
    }//GEN-LAST:event_eleccion_1MouseClicked

    private void eleccion_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_2MouseClicked
        jEditorPane1.setVisible(false);
        texto2.setVisible(true);
        texto3.setVisible(false);
        texto4.setVisible(false);
        texto5.setVisible(false);
        texto6.setVisible(false);
        pag1.setVisible(false);
        pag2.setVisible(true);
        pag3.setVisible(false);
        pag4.setVisible(false);
        pag5.setVisible(false);
        pag6.setVisible(false);
        pagina_actual_1.setVisible(false);
        pagina_actual_2.setVisible(true);
        pagina_actual_3.setVisible(false);
        pagina_actual_4.setVisible(false);
        pagina_actual_5.setVisible(false);
        pagina_actual_6.setVisible(false);
        P_siguiente_1.setVisible(false);
        P_siguiente_2.setVisible(true);
        P_siguiente_3.setVisible(false);
        P_siguiente_4.setVisible(false);
        P_siguiente_5.setVisible(false);
        P_regresar_1.setVisible(true);
        P_regresar_2.setVisible(false);
        P_regresar_3.setVisible(false);
        P_regresar_4.setVisible(false);
        P_regresar_5.setVisible(false);
        
    }//GEN-LAST:event_eleccion_2MouseClicked

    private void eleccion_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_3MouseClicked
        jEditorPane1.setVisible(false);
        texto2.setVisible(false);
        texto3.setVisible(true);
        texto4.setVisible(false);
        texto5.setVisible(false);
        texto6.setVisible(false);
        pag1.setVisible(false);
        pag2.setVisible(false);
        pag3.setVisible(true);
        pag4.setVisible(false);
        pag5.setVisible(false);
        pag6.setVisible(false);
        pagina_actual_1.setVisible(false);
        pagina_actual_2.setVisible(false);
        pagina_actual_3.setVisible(true);
        pagina_actual_4.setVisible(false);
        pagina_actual_5.setVisible(false);
        pagina_actual_6.setVisible(false);
        P_siguiente_1.setVisible(false);
        P_siguiente_2.setVisible(false);
        P_siguiente_3.setVisible(true);
        P_siguiente_4.setVisible(false);
        P_siguiente_5.setVisible(false);
        P_regresar_1.setVisible(false);
        P_regresar_2.setVisible(true);
        P_regresar_3.setVisible(false);
        P_regresar_4.setVisible(false);
        P_regresar_5.setVisible(false);
        
    }//GEN-LAST:event_eleccion_3MouseClicked

    private void eleccion_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_4MouseClicked
        jEditorPane1.setVisible(false);
        texto2.setVisible(false);
        texto3.setVisible(false);
        texto4.setVisible(true);
        texto5.setVisible(false);
        texto6.setVisible(false);
        pag1.setVisible(false);
        pag2.setVisible(false);
        pag3.setVisible(false);
        pag4.setVisible(true);
        pag5.setVisible(false);
        pag6.setVisible(false);
        pagina_actual_1.setVisible(false);
        pagina_actual_2.setVisible(false);
        pagina_actual_3.setVisible(false);
        pagina_actual_3.setVisible(false);
        pagina_actual_4.setVisible(true);
        pagina_actual_5.setVisible(false);
        pagina_actual_6.setVisible(false);
        P_siguiente_1.setVisible(false);
        P_siguiente_2.setVisible(false);
        P_siguiente_3.setVisible(false);
        P_siguiente_4.setVisible(true);
        P_siguiente_5.setVisible(false);
        P_regresar_1.setVisible(false);
        P_regresar_2.setVisible(false);
        P_regresar_3.setVisible(true);
        P_regresar_4.setVisible(false);
        P_regresar_5.setVisible(false);
        
    }//GEN-LAST:event_eleccion_4MouseClicked

    private void eleccion_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_5MouseClicked
        jEditorPane1.setVisible(false);
        texto2.setVisible(false);
        texto3.setVisible(false);
        texto4.setVisible(false);
        texto5.setVisible(true);
        texto6.setVisible(false);
        pag1.setVisible(false);
        pag2.setVisible(false);
        pag3.setVisible(false);
        pag4.setVisible(false);
        pag5.setVisible(true);
        pag6.setVisible(false);
        pagina_actual_1.setVisible(false);
        pagina_actual_2.setVisible(false);
        pagina_actual_3.setVisible(false);
        pagina_actual_3.setVisible(false);
        pagina_actual_4.setVisible(false);
        pagina_actual_5.setVisible(true);
        pagina_actual_6.setVisible(false);
        P_siguiente_1.setVisible(false);
        P_siguiente_2.setVisible(false);
        P_siguiente_3.setVisible(false);
        P_siguiente_4.setVisible(true);
        P_siguiente_5.setVisible(false);
        P_regresar_1.setVisible(false);
        P_regresar_2.setVisible(false);
        P_regresar_3.setVisible(false);
        P_regresar_4.setVisible(true);
        P_regresar_5.setVisible(false);
        
    }//GEN-LAST:event_eleccion_5MouseClicked

    private void eleccion_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eleccion_6MouseClicked
        jEditorPane1.setVisible(false);
        texto2.setVisible(false);
        texto3.setVisible(false);
        texto4.setVisible(false);
        texto5.setVisible(false);
        texto6.setVisible(true);
        pag1.setVisible(false);
        pag2.setVisible(false);
        pag3.setVisible(false);
        pag4.setVisible(false);
        pag5.setVisible(false);
        pag6.setVisible(true);
        pagina_actual_1.setVisible(false);
        pagina_actual_2.setVisible(false);
        pagina_actual_3.setVisible(false);
        pagina_actual_3.setVisible(false);
        pagina_actual_4.setVisible(false);
        pagina_actual_5.setVisible(false);
        pagina_actual_6.setVisible(true);
        P_siguiente_1.setVisible(false);
        P_siguiente_2.setVisible(false);
        P_siguiente_3.setVisible(false);
        P_siguiente_4.setVisible(false);
        P_siguiente_5.setVisible(false);
        P_regresar_1.setVisible(false);
        P_regresar_2.setVisible(false);
        P_regresar_3.setVisible(false);
        P_regresar_4.setVisible(false);
        P_regresar_5.setVisible(true);
        
    }//GEN-LAST:event_eleccion_6MouseClicked

    private void P_siguiente_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_siguiente_2MouseClicked
        jEditorPane1.setVisible(false);
        texto2.setVisible(false);
        texto3.setVisible(true);
        texto4.setVisible(false);
        texto5.setVisible(false);
        texto6.setVisible(false);
        pag1.setVisible(false);
        pag2.setVisible(false);
        pag3.setVisible(true);
        pag4.setVisible(false);
        pag5.setVisible(false);
        pag6.setVisible(false);
        P_siguiente_1.setVisible(false);
        P_siguiente_2.setVisible(false);
        P_siguiente_3.setVisible(true);
        P_siguiente_4.setVisible(false);
        P_siguiente_5.setVisible(false);
        pagina_actual_1.setVisible(false);
        pagina_actual_2.setVisible(false);
        pagina_actual_3.setVisible(true);
        pagina_actual_4.setVisible(false);
        pagina_actual_5.setVisible(false);
        pagina_actual_6.setVisible(false);
        P_regresar_1.setVisible(false);
        P_regresar_2.setVisible(true);
        P_regresar_3.setVisible(false);
        P_regresar_4.setVisible(false);
        P_regresar_5.setVisible(false);
        
    }//GEN-LAST:event_P_siguiente_2MouseClicked

    private void P_siguiente_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_siguiente_2MouseEntered
        P_siguiente_2.setBackground(Color.gray);
        siguiente_2.setForeground(Color.white);
    }//GEN-LAST:event_P_siguiente_2MouseEntered

    private void P_siguiente_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_siguiente_2MouseExited
        P_siguiente_2.setBackground(Color.white);
        siguiente_2.setForeground(Color.black);
    }//GEN-LAST:event_P_siguiente_2MouseExited

    private void P_siguiente_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_siguiente_3MouseClicked
        jEditorPane1.setVisible(false);
        texto2.setVisible(false);
        texto3.setVisible(false);
        texto4.setVisible(true);
        texto5.setVisible(false);
        texto6.setVisible(false);
        pag1.setVisible(false);
        pag2.setVisible(false);
        pag3.setVisible(false);
        pag4.setVisible(true);
        pag5.setVisible(false);
        pag6.setVisible(false);
        P_siguiente_1.setVisible(false);
        P_siguiente_2.setVisible(false);
        P_siguiente_3.setVisible(false);
        P_siguiente_4.setVisible(true);
        P_siguiente_5.setVisible(false);
        pagina_actual_1.setVisible(false);
        pagina_actual_2.setVisible(false);
        pagina_actual_3.setVisible(false);
        pagina_actual_4.setVisible(true);
        pagina_actual_5.setVisible(false);
        pagina_actual_6.setVisible(false);
        P_regresar_1.setVisible(false);
        P_regresar_2.setVisible(false);
        P_regresar_3.setVisible(true);
        P_regresar_4.setVisible(false);
        P_regresar_5.setVisible(false);
    }//GEN-LAST:event_P_siguiente_3MouseClicked

    private void P_siguiente_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_siguiente_3MouseEntered
        P_siguiente_3.setBackground(Color.gray);
        siguiente_3.setForeground(Color.white);
    }//GEN-LAST:event_P_siguiente_3MouseEntered

    private void P_siguiente_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_siguiente_3MouseExited
        P_siguiente_3.setBackground(Color.white);
        siguiente_3.setForeground(Color.black);
    }//GEN-LAST:event_P_siguiente_3MouseExited

    private void P_siguiente_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_siguiente_4MouseClicked
        texto2.setVisible(false);
        texto3.setVisible(false);
        texto4.setVisible(false);
        texto5.setVisible(true);
        texto6.setVisible(false);
        pag1.setVisible(false);
        pag2.setVisible(false);
        pag3.setVisible(false);
        pag4.setVisible(false);
        pag5.setVisible(true);
        pag6.setVisible(false);
        P_siguiente_1.setVisible(false);
        P_siguiente_2.setVisible(false);
        P_siguiente_3.setVisible(false);
        P_siguiente_4.setVisible(false);
        P_siguiente_5.setVisible(true);
        pagina_actual_1.setVisible(false);
        pagina_actual_2.setVisible(false);
        pagina_actual_3.setVisible(false);
        pagina_actual_4.setVisible(false);
        pagina_actual_5.setVisible(true);
        pagina_actual_6.setVisible(false);
        P_regresar_1.setVisible(false);
        P_regresar_2.setVisible(false);
        P_regresar_3.setVisible(false);
        P_regresar_4.setVisible(true);
        P_regresar_5.setVisible(false);
        
    }//GEN-LAST:event_P_siguiente_4MouseClicked

    private void P_siguiente_4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_siguiente_4MouseEntered
        P_siguiente_4.setBackground(Color.gray);
        siguiente_4.setForeground(Color.white);
    }//GEN-LAST:event_P_siguiente_4MouseEntered

    private void P_siguiente_4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_siguiente_4MouseExited
        P_siguiente_4.setBackground(Color.white);
        siguiente_4.setForeground(Color.black);
    }//GEN-LAST:event_P_siguiente_4MouseExited

    private void P_siguiente_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_siguiente_5MouseClicked
        texto2.setVisible(false);
        texto3.setVisible(false);
        texto4.setVisible(false);
        texto5.setVisible(false);
        texto6.setVisible(true);
        pag1.setVisible(false);
        pag2.setVisible(false);
        pag3.setVisible(false);
        pag4.setVisible(false);
        pag5.setVisible(false);
        pag6.setVisible(true);
        P_siguiente_1.setVisible(false);
        P_siguiente_2.setVisible(false);
        P_siguiente_3.setVisible(false);
        P_siguiente_4.setVisible(false);
        P_siguiente_5.setVisible(false);
        pagina_actual_1.setVisible(false);
        pagina_actual_2.setVisible(false);
        pagina_actual_3.setVisible(false);
        pagina_actual_4.setVisible(false);
        pagina_actual_5.setVisible(false);
        pagina_actual_6.setVisible(true);
        P_regresar_1.setVisible(false);
        P_regresar_2.setVisible(false);
        P_regresar_3.setVisible(false);
        P_regresar_4.setVisible(false);
        P_regresar_5.setVisible(true);
    }//GEN-LAST:event_P_siguiente_5MouseClicked

    private void P_siguiente_5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_siguiente_5MouseEntered
        P_siguiente_5.setBackground(Color.gray);
        siguiente_5.setForeground(Color.white);
    }//GEN-LAST:event_P_siguiente_5MouseEntered

    private void P_siguiente_5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_siguiente_5MouseExited
        P_siguiente_5.setBackground(Color.white);
        siguiente_5.setForeground(Color.black);
    }//GEN-LAST:event_P_siguiente_5MouseExited

    private void regreso_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regreso_1MouseClicked
        jEditorPane1.setVisible(true);
        texto2.setVisible(false);
        texto3.setVisible(false);
        texto4.setVisible(false);
        texto5.setVisible(false);
        texto6.setVisible(false);
        pag1.setVisible(true);
        pag2.setVisible(false);
        pag3.setVisible(false);
        pag4.setVisible(false);
        pag5.setVisible(false);
        pag6.setVisible(false);
        P_siguiente_1.setVisible(true);
        P_siguiente_2.setVisible(false);
        P_siguiente_3.setVisible(false);
        P_siguiente_4.setVisible(false);
        P_siguiente_5.setVisible(false);
        pagina_actual_1.setVisible(true);
        pagina_actual_2.setVisible(false);
        pagina_actual_3.setVisible(false);
        pagina_actual_4.setVisible(false);
        pagina_actual_5.setVisible(false);
        pagina_actual_6.setVisible(false);
        P_regresar_1.setVisible(false);
        P_regresar_2.setVisible(false);
        P_regresar_3.setVisible(false);
        P_regresar_4.setVisible(false);
        P_regresar_5.setVisible(false);
    }//GEN-LAST:event_regreso_1MouseClicked

    private void regreso_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regreso_2MouseClicked
        jEditorPane1.setVisible(false);
        texto2.setVisible(true);
        texto3.setVisible(false);
        texto4.setVisible(false);
        texto5.setVisible(false);
        texto6.setVisible(false);
        pag1.setVisible(false);
        pag2.setVisible(true);
        pag3.setVisible(false);
        pag4.setVisible(false);
        pag5.setVisible(false);
        pag6.setVisible(false);
        P_siguiente_1.setVisible(false);
        P_siguiente_2.setVisible(true);
        P_siguiente_3.setVisible(false);
        P_siguiente_4.setVisible(false);
        P_siguiente_5.setVisible(false);
        pagina_actual_1.setVisible(false);
        pagina_actual_2.setVisible(true);
        pagina_actual_3.setVisible(false);
        pagina_actual_4.setVisible(false);
        pagina_actual_5.setVisible(false);
        pagina_actual_6.setVisible(false);
        P_regresar_1.setVisible(true);
        P_regresar_2.setVisible(false);
        P_regresar_3.setVisible(false);
        P_regresar_4.setVisible(false);
        P_regresar_5.setVisible(false);
        
    }//GEN-LAST:event_regreso_2MouseClicked

    private void regreso_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regreso_3MouseClicked
        jEditorPane1.setVisible(false);
        texto2.setVisible(false);
        texto3.setVisible(true);
        texto4.setVisible(false);
        texto5.setVisible(false);
        texto6.setVisible(false);
        pag1.setVisible(false);
        pag2.setVisible(false);
        pag3.setVisible(true);
        pag4.setVisible(false);
        pag5.setVisible(false);
        pag6.setVisible(false);
        P_siguiente_1.setVisible(false);
        P_siguiente_2.setVisible(false);
        P_siguiente_3.setVisible(true);
        P_siguiente_4.setVisible(false);
        P_siguiente_5.setVisible(false);
        pagina_actual_1.setVisible(false);
        pagina_actual_2.setVisible(false);
        pagina_actual_3.setVisible(true);
        pagina_actual_4.setVisible(false);
        pagina_actual_5.setVisible(false);
        pagina_actual_6.setVisible(false);
        P_regresar_1.setVisible(false);
        P_regresar_2.setVisible(true);
        P_regresar_3.setVisible(false);
        P_regresar_4.setVisible(false);
        P_regresar_5.setVisible(false);
    }//GEN-LAST:event_regreso_3MouseClicked

    private void regreso_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regreso_4MouseClicked
        jEditorPane1.setVisible(false);
        texto2.setVisible(false);
        texto3.setVisible(false);
        texto4.setVisible(true);
        texto5.setVisible(false);
        texto6.setVisible(false);
        pag1.setVisible(false);
        pag2.setVisible(false);
        pag3.setVisible(false);
        pag4.setVisible(true);
        pag5.setVisible(false);
        pag6.setVisible(false);
        P_siguiente_1.setVisible(false);
        P_siguiente_2.setVisible(false);
        P_siguiente_3.setVisible(false);
        P_siguiente_4.setVisible(true);
        P_siguiente_5.setVisible(false);
        pagina_actual_1.setVisible(false);
        pagina_actual_2.setVisible(false);
        pagina_actual_3.setVisible(false);
        pagina_actual_4.setVisible(true);
        pagina_actual_5.setVisible(false);
        pagina_actual_6.setVisible(false);
        P_regresar_1.setVisible(false);
        P_regresar_2.setVisible(false);
        P_regresar_3.setVisible(true);
        P_regresar_4.setVisible(false);
        P_regresar_5.setVisible(false);
        
    }//GEN-LAST:event_regreso_4MouseClicked

    private void regreso_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regreso_5MouseClicked
        jEditorPane1.setVisible(false);
        texto2.setVisible(false);
        texto3.setVisible(false);
        texto4.setVisible(false);
        texto5.setVisible(true);
        texto6.setVisible(false);
        pag1.setVisible(false);
        pag2.setVisible(false);
        pag3.setVisible(false);
        pag4.setVisible(false);
        pag5.setVisible(true);
        pag6.setVisible(false);
        P_siguiente_1.setVisible(false);
        P_siguiente_2.setVisible(false);
        P_siguiente_3.setVisible(false);
        P_siguiente_4.setVisible(false);
        P_siguiente_5.setVisible(true);
        pagina_actual_1.setVisible(false);
        pagina_actual_2.setVisible(false);
        pagina_actual_3.setVisible(false);
        pagina_actual_4.setVisible(false);
        pagina_actual_5.setVisible(true);
        pagina_actual_6.setVisible(false);
        P_regresar_1.setVisible(false);
        P_regresar_2.setVisible(false);
        P_regresar_3.setVisible(false);
        P_regresar_4.setVisible(true);
        P_regresar_5.setVisible(false);
        
    }//GEN-LAST:event_regreso_5MouseClicked

    private void P_regresar_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_regresar_1MouseEntered
        P_siguiente_1.setBackground(Color.gray);
        siguiente_1.setForeground(Color.white);
    }//GEN-LAST:event_P_regresar_1MouseEntered

    private void P_regresar_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_regresar_1MouseExited
        P_siguiente_1.setBackground(Color.white);
        siguiente_1.setForeground(Color.black);
    }//GEN-LAST:event_P_regresar_1MouseExited

    private void P_regresar_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_regresar_2MouseEntered
        P_siguiente_1.setBackground(Color.gray);
        siguiente_1.setForeground(Color.white);
    }//GEN-LAST:event_P_regresar_2MouseEntered

    private void P_regresar_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_regresar_2MouseExited
        P_siguiente_1.setBackground(Color.white);
        siguiente_1.setForeground(Color.black);
    }//GEN-LAST:event_P_regresar_2MouseExited

    private void P_regresar_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_regresar_3MouseEntered
        P_siguiente_1.setBackground(Color.gray);
        siguiente_1.setForeground(Color.white);
    }//GEN-LAST:event_P_regresar_3MouseEntered

    private void P_regresar_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_regresar_3MouseExited
        P_siguiente_1.setBackground(Color.white);
        siguiente_1.setForeground(Color.black);
    }//GEN-LAST:event_P_regresar_3MouseExited

    private void P_regresar_4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_regresar_4MouseEntered
        P_siguiente_1.setBackground(Color.gray);
        siguiente_1.setForeground(Color.white);
    }//GEN-LAST:event_P_regresar_4MouseEntered

    private void P_regresar_4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_regresar_4MouseExited
        P_siguiente_1.setBackground(Color.white);
        siguiente_1.setForeground(Color.black);
    }//GEN-LAST:event_P_regresar_4MouseExited

    private void P_regresar_5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_regresar_5MouseEntered
        P_siguiente_1.setBackground(Color.gray);
        siguiente_1.setForeground(Color.white);
    }//GEN-LAST:event_P_regresar_5MouseEntered

    private void P_regresar_5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_regresar_5MouseExited
        P_siguiente_1.setBackground(Color.white);
        siguiente_1.setForeground(Color.black);
    }//GEN-LAST:event_P_regresar_5MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
  
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        
    }//GEN-LAST:event_jPanel2MouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
           
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
       
    }//GEN-LAST:event_formMouseDragged

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        mousex = evt.getX();
        mousey = evt.getY();   
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mousex, y - mousey);
    }//GEN-LAST:event_jButton2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new libro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P_regresar_1;
    private javax.swing.JPanel P_regresar_2;
    private javax.swing.JPanel P_regresar_3;
    private javax.swing.JPanel P_regresar_4;
    private javax.swing.JPanel P_regresar_5;
    private javax.swing.JPanel P_siguiente_1;
    private javax.swing.JPanel P_siguiente_2;
    private javax.swing.JPanel P_siguiente_3;
    private javax.swing.JPanel P_siguiente_4;
    private javax.swing.JPanel P_siguiente_5;
    private javax.swing.JPanel eleccion_1;
    private javax.swing.JPanel eleccion_2;
    private javax.swing.JPanel eleccion_3;
    private javax.swing.JPanel eleccion_4;
    private javax.swing.JPanel eleccion_5;
    private javax.swing.JPanel eleccion_6;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pag1;
    private javax.swing.JPanel pag2;
    private javax.swing.JPanel pag3;
    private javax.swing.JPanel pag4;
    private javax.swing.JPanel pag5;
    private javax.swing.JPanel pag6;
    private javax.swing.JLabel pagina_actual_1;
    private javax.swing.JLabel pagina_actual_2;
    private javax.swing.JLabel pagina_actual_3;
    private javax.swing.JLabel pagina_actual_4;
    private javax.swing.JLabel pagina_actual_5;
    private javax.swing.JLabel pagina_actual_6;
    private javax.swing.JLabel regreso_1;
    private javax.swing.JLabel regreso_2;
    private javax.swing.JLabel regreso_3;
    private javax.swing.JLabel regreso_4;
    private javax.swing.JLabel regreso_5;
    private javax.swing.JLabel siguiente_1;
    private javax.swing.JLabel siguiente_2;
    private javax.swing.JLabel siguiente_3;
    private javax.swing.JLabel siguiente_4;
    private javax.swing.JLabel siguiente_5;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    private javax.swing.JLabel texto5;
    private javax.swing.JLabel texto6;
    private javax.swing.JLabel textobasura8;
    private javax.swing.JLabel textobasura9;
    private javax.swing.JLabel vinculo_1;
    private javax.swing.JLabel vinculo_2;
    private javax.swing.JLabel vinculo_3;
    private javax.swing.JLabel vinculo_4;
    private javax.swing.JLabel vinculo_5;
    private javax.swing.JLabel vinculo_6;
    private javax.swing.JLabel xd;
    // End of variables declaration//GEN-END:variables
}
